### ISSUE TITLE
ILP does not handle duplicate fields in the message

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#1213] opened 2021-07-21 10:18 UTC
**Describe the bug**
ILP messes data if message has duplicate filed tags

**To Reproduce**
Send
```
weather alpha=0.1,speed=1,speed=2
weather alpha=0.2
weather timestamp=9831289
```

This will result in messed data at line 2 having `speed` = 2 and line 3 `timestamp` in 1970

**Expected behavior**
Reject line or take either first or last value of duplicated fileds. Reject lines where designated timestamp is specified as a field

**Screenshots**

**Environment (please complete the following information):**
 - Version: [e.g. 5.0.4]

**Additional context**
related to #1212 

Can be reproduced with following test in LineTcpServerTest.java 

```Java
    @Test
    public void testDubFieldValues() throws Exception {
        String lineData =
                "weather g=1,a=0.1,windspeed=1.0 0\n" +
                "weather g=2,windspeed=2.0,windspeed=3.0 60000000000\n" +
                "weather g=3,a=0.4,a=0.5 120000000000\n"+
                "weather g=4,a=0.7,windspeed=67.72 180000000000\n";

        runInContext(() -> {
            send(lineData, "weather", true, false);

            String expected =
                    "g\ta\twindspeed\ttimestamp\n" +
                            "1.0\t0.1\t1.0\t1970-01-01T00:00:00.000000Z\n" +
                            "2.0\tNaN\t2.0\t1970-01-01T00:01:00.000000Z\n" +
                            "3.0\t0.4\tNaN\t1970-01-01T00:02:00.000000Z\n" +
                            "4.0\t0.67\t67.72\t1970-01-01T0:03:00.000000Z\n";
            assertTable(expected, "weather");
        });
    }

```

**Comment by EvgenySergeychik** [comment] 2021-10-04 01:54
It looks like the behavior for duplicated tags is only reproduced when the table is created with all the fields first:
weather alpha=0.1,speed=1
weather alpha=0.1,speed=1,speed=2
weather alpha=0.2

**Comment by EvgenySergeychik** [comment] 2021-10-04 23:40
Thank you for the test case Alex.
It look tho that you made a typo in the expected value in the last line for column a which should have value of 0.7 instead of 0.67.
I put the following pr for fixing duplicates:

https://github.com/questdb/questdb/pull/1388/files

The idea is to skip ProtoEntity by not incrementing value of nEntities and let the parser continue to parse the rest of the measurement.

**Comment by ideoma** [comment] 2021-11-22 15:32
I think the problem is better to attack on storage level, not only ILP has the problem of pushing same column twice in a row, embedded API can also do the same, here how it happened in another issue

https://github.com/questdb/questdb/issues/1338

**Comment by laa** [comment] 2021-11-23 08:28
Hi @ideoma .
May I ask you a question?
Your initial proposal for this issue was to choose one of the values of duplicated fields. But it does not seem to be correct for me. You see user provides a not well-formed message.  Likely there is a bug in the code that produces such messages as result accepting not well-formed messages allows users to miss mistakes and have unexpended behaviour in the future. 
Would not be better to throw an exception instead?

**Comment by laa** [comment] 2021-11-23 08:31
Also about your opinion, that issue has to be fixed on storage level. Despite the fact storage API for sure should validate incorrect usage and throw exception/autocorrect user behaviour parser itself IMHO should not tolerate not-well formed messages. Relying on the behaviour of an underlying component for validation of messages creates a bit longer chain of dependencies and increases the risk of regressions in future. WDYT ?

**Comment by puzpuzpuz** [comment] 2021-11-23 08:55
> Would not be better to throw an exception instead?

There is no notion of an exception/error in the context of ILP. The only options are to ignore the malformed row optionally writing a log message, or ingest it somehow, or forcefully close the socket. The third option is somewhat we don't want to do, so we have only two options here.

> Despite the fact storage API for sure should validate incorrect usage and throw exception/autocorrect user behaviour parser itself IMHO should not tolerate not-well formed messages. Relying on the behaviour of an underlying component for validation of messages creates a bit longer chain of dependencies and increases the risk of regressions in future. WDYT ?

The thing is that the storage API, or at least a certain part of it, is what's directly exposed to the end user. I mean `Row` interface and `TableWriter.RowImpl` class. This implementation is also used for ILP ingestion, so if we make it less fragile to the user code mistakes, we'll kill two birds with one stone.

**Comment by ideoma** [comment] 2021-11-23 09:16
Rejecting a line in ILP is an option too. 

I believe the fastest solution should take a priority out of rejecting, setting first value, setting last value or adding another column with <name>_1 with the value. The latest is in spirit of ILP specification but least of my personal favourite since I think it's best of Influx storage model but not ours.

It's not necessary to do it on storage level tbh, perhaps it is too much overhead for other ways to insert data than embedded API. As Adrey said it's just about killing 2 birds.

**Comment by laa** [comment] 2021-11-23 13:41
@ideoma @puzpuzpuz thank you for your answers in such a case I would prefer to reject "incorrect" rows.

**Comment by OmgImAlexis** [comment] 2021-11-23 21:21
> @ideoma @puzpuzpuz thank you for your answers in such a case I would prefer to reject "incorrect" rows.

Same here. Especially when UPDATE/DELETE isn't yet supported. It means any bad line can taint the whole dataset.

**Closed** 2021-12-13 16:23 UTC
Labels: Bug
