### ISSUE TITLE
Speed up SAMPLE BY when aggregated on many time intervals / groups

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#795] opened 2021-02-02 16:57 UTC
**Is your feature request related to a problem? Please describe.**
Running sample by aggregation on table with 10k rows takes surprisingly long time (around 40s) when timeframe is too low to aggregate anything.

```
create table metrics as
(
select rnd_symbol('AA', 'BB', 'CC') box,
rnd_double() seq,
timestamp_sequence(182800000000, 360000000) ts
from long_sequence(10000) 
) timestamp (ts)

select box, avg(seq), ts from metrics sample by 2m 
```

**Comment by bluestreak01** [comment] 2021-05-18 10:05
duplicate of #369

**Closed by bluestreak01** 2021-05-18 10:05 UTC
Labels: New feature
