### ISSUE TITLE
assertion error on a case issue

### ISSUE THREAD

**Issue by vbmithr** [questdb/questdb#2894] opened 2023-01-01 18:56 UTC
### Describe the bug

```
2023-01-01T18:52:59.236613Z I i.q.g.SqlCompiler batch [text=WITH syms AS (SELECT 'BTCUSDT')
SELECT tr.ts, tr.sym, AVG(px) px, SUM(qty) qty, SUM(ABS(qty)) absqty, COUNT() cnt, round(AVG(px)*SUM(ABS(qty)),0) usdqty,
       FIRST(A) op, last(A) cl, round(10000*(log(LAST(A))-log(FIRST(A))), 2) bpschg
  FROM (SELECT * FROM trade WHERE sym IN (SELECT * FROM syms)) AS tr
         asof JOIN (SELECT * FROM quote WHERE sym IN (SELECT * FROM syms)) AS qu
                     sample BY 10s
 ORDER BY absqty DESC
 LIMIT 20 ;]
2023-01-01T18:52:59.251130Z C i.q.c.p.PGWireServer internal error [ex=
java.lang.AssertionError
        at io.questdb.std.ObjList.getQuick(ObjList.java:173)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause0(SqlOptimiser.java:3158)
        at io.questdb.griffin.SqlOptimiser.rewriteSelectClause(SqlOptimiser.java:2975)
        at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:3546)
        at io.questdb.griffin.SqlCompiler.compileExecutionModel(SqlCompiler.java:1112)
        at io.questdb.griffin.SqlCompiler.compileUsingModel(SqlCompiler.java:1193)
        at io.questdb.griffin.SqlCompiler.compileInner(SqlCompiler.java:1146)
        at io.questdb.griffin.SqlCompiler.compileBatch(SqlCompiler.java:314)
        at io.questdb.cutlass.pgwire.PGConnectionContext.processQuery(PGConnectionContext.java:2237)
        at io.questdb.cutlass.pgwire.PGConnectionContext.parse(PGConnectionContext.java:1557)
        at io.questdb.cutlass.pgwire.PGConnectionContext.handleClientOperation(PGConnectionContext.java:385)
        at io.questdb.cutlass.pgwire.PGJobContext.handleClientOperation(PGJobContext.java:89)
        at io.questdb.cutlass.pgwire.PGWireServer$1.lambda$$0(PGWireServer.java:83)
        at io.questdb.network.AbstractIODispatcher.processIOQueue(AbstractIODispatcher.java:169)
        at io.questdb.cutlass.pgwire.PGWireServer$1.run(PGWireServer.java:110)
        at io.questdb.mp.Worker.run(Worker.java:118)
]
```

When writing `LAST(A) cl` instead of `last(A) cl`, it works fine. `last(a)` also fails.

### Environment

```markdown
- **QuestDB version**: 6.6.1
- **OS**: Linux
- **Browser**:
```

**Comment by bziobrowski** [comment] 2023-01-03 11:27
Duplicate of #2892

**Comment by puzpuzpuz** [comment] 2023-01-04 09:31
Closing as a duplicate of #2892. Feel free to reopen if you think it's a different bug.

**Closed by puzpuzpuz** 2023-01-04 09:31 UTC
Labels: Bug, SQL
