### ISSUE TITLE
Embedded: Very high memory usage on startup

### ISSUE THREAD

**Issue by nu11ptr** [questdb/questdb#1211] opened 2021-07-20 22:36 UTC
**Describe the bug**
I'm not sure there is a bug here, however, when simply initializing QuestDB as an embedded database, a whopping 220MB of extra heap space is used (measured AFTER full GC). No DB operations are performed other than startup and no database is present (empty). I understand that to be high performance might be a trade off with higher memory usage, but it seems like memory should only be 'paid for' if used? Or is this some sort of startup cache that can be tuned?

**To Reproduce**
1. Startup any Java (or in my case, Kotlin) application - can be "hello world" as long as it doesn't terminate
2. Open `VisualVM` - perform a full GC and note down heap usage
3. Close program, and modify with these lines in one of the classes (ensuring the references are not released of course)

```Java
    private var config = new DefaultCairoConfiguration("./")
    private var engine = new CairoEngine(config)
```

4. Open `VisualVM` - perform a full GC and note down heap usage

The difference between heap usage in steps 4 and step 1 is 220MB (at least in my application, 30MB before, 250MB after)

**Expected behavior**
I expected heap usage to be minimal until I performed data transactions at which point I'd hope it would be tunable ideally based on my desire for in app caching

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux (amd64), OpenJDK 11 64-bit
 - Browser: not relevant
 - Version: PopOS 20.04

**Additional context**
Using QuestDB 6.0.4

**Comment by bluestreak01** [comment] 2021-07-20 22:40
We're reading and indexing Java's timezone database. Unfortunately this database is available via very dirty in terms of heap API. All of the garbage generated during this process is transient. `System.gc()` will discard most of that.

**Comment by nu11ptr** [comment] 2021-07-20 22:42
This is AFTER full GC. Before I do the GC in Visual VM it is much higher. 220MB is retained heap memory by QuestDB alone after init.

**Comment by nu11ptr** [comment] 2021-07-21 02:00
I further narrowed it down to `DefaultCairoConfiguration`. `CairoEngine` usage is negligible and omitting it made almost no difference. I ran a Java Object Layout on the former and got this output:
```
io.questdb.cairo.DefaultCairoConfiguration@1e4b908ad footprint:
     COUNT       AVG       SUM   DESCRIPTION
   1045990        41  43821064   [B
      4938       190    941056   [I
      1200       568    681984   [J
         2        80       160   [Lio.questdb.std.ConcurrentHashMap$Node;
         2      8208     16416   [Ljava.lang.CharSequence;
     41472       187   7787776   [Ljava.lang.Object;
      4482        48    215136   [Ljava.lang.String;
         1        24        24   io.questdb.BuildInformationHolder
         1        16        16   io.questdb.DefaultTelemetryConfiguration
         1        48        48   io.questdb.cairo.DefaultCairoConfiguration
         1        16        16   io.questdb.cutlass.text.DefaultTextConfiguration
         1        80        80   io.questdb.cutlass.text.types.InputFormatConfiguration
         1        48        48   io.questdb.std.CharSequenceIntHashMap
         1        48        48   io.questdb.std.CharSequenceObjHashMap
         2        72       144   io.questdb.std.ConcurrentHashMap
         1        16        16   io.questdb.std.ConcurrentHashMap$$Lambda$760/0x000000084066a440
         2        24        48   io.questdb.std.ConcurrentHashMap$EntrySetView
         1        16        16   io.questdb.std.ConcurrentHashMap$EntrySetView$$Lambda$785/0x00000008406d9840
         5        32       160   io.questdb.std.ConcurrentHashMap$Node
         2        24        48   io.questdb.std.IntList
      3735        48    179280   io.questdb.std.IntObjHashMap
      1200        32     38400   io.questdb.std.LongList
     37736        24    905664   io.questdb.std.ObjList
         1        16        16   io.questdb.std.datetime.DateFormatAsm/0x00000008406d9c40
         1        16        16   io.questdb.std.datetime.DateFormatAsm/0x00000008406da040
         1        16        16   io.questdb.std.datetime.DateFormatAsm/0x00000008406da440
         1        16        16   io.questdb.std.datetime.DateFormatAsm/0x00000008406da840
       747        64     47808   io.questdb.std.datetime.DateLocale
         1        16        16   io.questdb.std.datetime.DateLocaleFactory
         6        24       144   io.questdb.std.datetime.FixedTimeZoneRule
         1        24        24   io.questdb.std.datetime.TimeZoneRuleFactory
         1        16        16   io.questdb.std.datetime.TimestampFormatAsm/0x00000008406dac40
       864        56     48384   io.questdb.std.datetime.TransitionRule
       600        72     43200   io.questdb.std.datetime.microtime.TimeZoneRulesMicros
         1        16        16   io.questdb.std.datetime.microtime.TimestampFormatFactory
         1        16        16   io.questdb.std.datetime.millitime.DateFormatFactory
       600        72     43200   io.questdb.std.datetime.millitime.TimeZoneRulesMillis
   1045990        24  25103760   java.lang.String
         4        24        96   java.lang.ThreadLocal$SuppliedThreadLocal
   2189597            79874392   (total)
```

At a glance I can see 43MB of byte arrays, 25MB of strings, and 8MB of generic object arrays. I'm not that familiar with this tool, so not sure why it only finds 80MB when I can see the difference this one instance makes is 220MB in the profiler, so almost 3x that amount. Regardless, it is a start. Hope that helps.

BTW, this is the snippet I used to dump the object (in Kotlin, `init` is just the constructor more or less):

```Kotlin
    private val config = DefaultCairoConfiguration(dataDir)

    init {
        System.gc()
        println(GraphLayout.parseInstance(config).toFootprint())
    }
```

**Comment by bluestreak01** [comment] 2021-08-13 09:00
We eagerly load the whole of the timezone database and all languages for that. Initialization is static, mainly via logger. Anything that logs will cause this library to be loaded.

As a solution I am thinking along the lines of lazily loading languages (not all of the required at the same time) and perhaps devising a new structure for the index. Existing index was a bit of a rush job.

The entry points into this infra are:

```
DateLocaleFactory
TimeZoneRuleFactory
```

**Comment by nu11ptr** [comment] 2021-08-17 15:29
This results in 220MB of heap usage? Interesting... I've actually now written my own time series DB (very basic, just partitioned binary files) since my requirements are extremely basic. QuestDB was probably always overkill for my small app, but if you ever find a way to drastically reduce this, I'll probably move back (since all the performance work you have done would be nice to have - but 220mb of extra heap is too big of a cost for this app). Thanks for looking at this.

**Comment by eugenels** [comment] 2021-09-23 16:11
>it only finds 80MB when I can see the difference this one instance makes is 220MB in the profiler, so almost 3x that amount.

The difference you are observing is the native memory is pre-allocated by the internal HTTP server and other ingestion protocol handlers. If you don’t need them for your embedded usage, you can simply turn them off via configuration.

Configuration options:
```
http.enabled=false
http.min.enabled=false
line.udp.enabled=false
line.tcp.enabled=false
pg.enabled=false
```

**Comment by nu11ptr** [comment] 2021-09-23 16:20
> The difference you are observing is the native memory is pre-allocated by the internal HTTP server and other ingestion protocol handlers. If you don’t need them for your embedded usage, you can simply turn them off via configuration.

Didn't realize that - I don't need those things so that will help a lot. Thanks for the tip.

**Comment by bsmth** [comment] 2021-09-24 08:11
Hi @nu11ptr it looks like @eugenels has found the cause of the problem, so I will close this issue for now. If this has not resolved high memory usage, feel free to re-open the issue and share your findings!

Thanks a lot 🙌🏻

**Closed by bsmth** 2021-09-24 08:11 UTC
