### ISSUE TITLE
Add comments (documentation) to the config file

### ISSUE THREAD

**Issue by mpsq** [questdb/questdb#302] opened 2020-05-18 16:33 UTC
The configuration file holds many parameters already. Some of them are obvious to the user, others could benefit from extra documentation.

A nice way of doing this is adding comments directly to [the config file](https://github.com/questdb/questdb/blob/master/core/src/test/resources/server.conf).

**Comment by bluestreak01** [comment] 2020-05-18 16:41
duplicate of #199

**Closed by bluestreak01** 2020-05-18 16:41 UTC
Labels: documentation
