### ISSUE TITLE
Invalid column in join 2 tables with same column name

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#970] opened 2021-05-05 09:02 UTC
**Describe the bug**
When joining to tables on the same column name SQL error happens

**To Reproduce**
```SQL
create table l as
( select x from long_sequence(100) )

create table r as
( select x + 50 from long_sequence(100) )

select x
from l join r on l.x = r.x

```
and got back
Invalid column: r.x

**Expected behavior**
Tables should be joined, no SQL syntax error

**Environment (please complete the following information):**
 - Version:6.0, 0b2bcb385215a95fc74d6825a5251eb1f27133e2

**Comment by bluestreak01** [comment] 2021-05-05 17:38
could be a duplicate of https://github.com/questdb/questdb/issues/865

**Comment by Ahmed-Elkholy** [comment] 2021-11-05 12:43
I think that the column in the **y** table is not named as **x**. It is given "column" as a name since no alias was provided.
![image](https://user-images.githubusercontent.com/26124176/140511392-e5a3c196-8dcb-4506-98a7-865dc28aea55.png)

Adding x alias to `x + 50` to the create query fixes the issue.

`create table r as
( select x + 50 as x from long_sequence(100) )`

**Comment by bluestreak01** [comment] 2021-11-10 16:48
haha, thank you! 👍

**Closed by bluestreak01** 2021-11-10 16:48 UTC
Labels: Bug, SQL, Good first issue, Hacktoberfest
