### ISSUE TITLE
Add Update and Delete

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#163] opened 2020-04-18 07:04 UTC
**Is your feature request related to a problem? Please describe.**

Even when dealing with time-series data, not all data will be TS data unless is very specific domains and application. Instead of using another DB for regular data, it will be good if you can UPDATE and DELETE data. Maybe you can specify certain tables as append-only which will further optimise these tables.

**Describe the solution you'd like**

Support TS tables and regular tables with UPDATE and DELETE.

This way you can use 1 DB for all your needs than different DBs as speciality solution when you need TS capabilities.

**Describe alternatives you've considered**

[Apache Ignite](https://ignite.apache.org/), [CrateDB](https://crate.io/) has the ability to deal with time series and regular data.

**Comment by bluestreak01** [comment] 2020-04-19 10:26
Although we do not support UPDATE and DELETE SQL statements we do support CRUD:

https://www.questdb.io/docs/crudOperations

Perhaps we can narrow this issue down when we take into account what's documented?

**Comment by sirinath** [comment] 2020-04-19 10:46
I guess this can be simulated.

**Comment by sirinath** [comment] 2020-04-19 12:56
I believe and alternative syntax might be helpful. To differentiate it from the SQL `update` it can be called `update latest`. This takes the last `latest` changes a few items and appends it as the new `latest`.

```sql
update latest balances 
set balance = 660.50, timestamp = 6000000005
where cust_id = 1;
```

and/or

```sql
update latest balances 
set (balance, timestamp)  = (660.50, 6000000005)
where cust_id = 1;
```

Having to insert `balance_ccy` can lead to errors and overhead. This is when only few items change.

This is just an idea for shorthand but not absolutely needed, but goo to have.

**Comment by g-metan** [comment] 2021-08-06 15:33
> https://www.questdb.io/docs/crudOperations

This URL is no longer valid (404 Not Found)

**Comment by bsmth** [comment] 2021-08-30 16:32
Closing as this is a duplicate of https://github.com/questdb/questdb/issues/262

**Closed by bsmth** 2021-08-30 16:32 UTC

**Comment by OmgImAlexis** [comment] 2021-11-14 21:29
@bsmth that other issue only covers "update", did you want to rename that or should this be reopened and renamed to "delete"?

**Comment by bluestreak01** [comment] 2021-11-14 21:32
We introduced "roadmap" recently. Both issues are already covered: [update](https://github.com/questdb/roadmap/issues/7) and [delete](https://github.com/questdb/roadmap/issues/10)
