### ISSUE TITLE
High Disk usage!?

### ISSUE THREAD

**Issue by Roh-codeur** [questdb/questdb#2895] opened 2023-01-01 21:20 UTC
### Describe the bug

Hi 

this is an awesome product, very impressive. I have been trying it out and comparing to some other time series databases as well. 

Quick one: it appears that it can use up a lot of disk space. for instance, I have a OHLCV table with 6052159 rows. I have a date, timestamp, ticker(Symbol) and OHLCV columns. the OHLCV db directory seems to take up close to 20GB disk space. 

- this appears quite high, no? is this expected?
- is there a way we can reduce disk usage by tables?

ta! 

### Environment

```markdown
- **QuestDB version**: 6.6.1
- **OS**: M1 Mac Monterey
- **Browser**: Safari
```

**Comment by ideoma** [comment] 2023-01-03 09:14
The record length would be 8+8+4+8*5=60 bytes. With 6052159 rows it should be 346Mb.

Please post create table statement and `du -sh *` inside the table directory to find out why you have unexpected high disk consumption.

**Comment by puzpuzpuz** [comment] 2023-01-03 09:19
You could also try ZFS with enabled compression to save some disk space (compression ratio should be around 2-3x with the default LZ4 algorithm). Just keep in mind that ZFS is not something we have tested and, thus, there is no official support for this file system (however, this may change in future).

**Comment by Roh-codeur** [comment] 2023-01-03 20:57
@ideoma : sure please see below. please note I removed some dirs from the du -sh output. Hope this helps

```
DROP TABLE IF EXISTS ohlcv;

CREATE TABLE ohlcv(
        Ticker SYMBOL CAPACITY 10000,
        Exchange SYMBOL CAPACITY 50,
        DataSource SYMBOL CAPACITY 50,
        Date TIMESTAMP,
        Open double,
        High double,
        Low double,
        Close double,
        AdjustedClose double,
        Volume double,
        timestamp TIMESTAMP)
  TIMESTAMP(date) 
  PARTITION BY MONTH;
```

```
cd /opt/homebrew/var/questdb/db/ohlcv

du -sh *
 65M	2000-01.592
 66M	2000-02.592
 66M	2000-03.592
 66M	2000-04.592
....
 90M	2022-10.592
 90M	2022-11.592
 16K	DataSource.c
 16K	DataSource.k
 16K	DataSource.o
 16K	DataSource.v
 16K	Exchange.c
 16K	Exchange.k
 16K	Exchange.o
 16K	Exchange.v
 48K	Ticker.c
 16K	Ticker.k
 16K	Ticker.o
 32K	Ticker.v
 16K	_cv
 16K	_meta
 16K	_meta.prev
 16K	_todo_
 32K	_txn
 36K	_txn_scoreboard

```

**Comment by Roh-codeur** [comment] 2023-01-03 21:03
@puzpuzpuz : sure, thanks. I will look into this as well.

**Comment by ideoma** [comment] 2023-01-03 23:49
Something does not add up. Your record size is 68 bytes and there is 65+Mb per monthly partition, it should be around 1M rows per month. In 22 years it should be about 264M rows, not 6M as you said.

What does QuestDB returns in `select count(*) from ohclv`?

**Comment by Roh-codeur** [comment] 2023-01-04 19:58
> What does QuestDB returns in `select count(*) from ohclv`?

it lists out 6,052,159. I have rows per ticker. not all tickers have data for 22 years, some only have data for a couple of years, or for a few months. 

```
cd /opt/homebrew/var/questdb/db
du -sh ohlcv/
 19G	ohlcv/
```

**Comment by ideoma** [comment] 2023-01-04 20:42
How many row it is in the first partition which is `2000-01` and takes 66Mb?

```
select count(*) from ohclv where timestamp in '2000-01'
```

It should be near 1M rows as per row size. If it's not then list the files in the folder with the sizes please. If it is, there must be a partition folder where the size on the disk does not match record count return by the query would be good if you can find and list the files there.

**Comment by Roh-codeur** [comment] 2023-01-04 20:50
> How many row it is in the first partition which is `2000-01` and takes 66Mb?
> 
> ```
> select count(*) from ohclv where timestamp in '2000-01'
> ```
> 

it comes out as 9864. Also, the query was:
`select count(*) from ohlcv where date in '2000-01';
`
```
cd /opt/homebrew/var/questdb/db/ohlcv/2000-01.592

du -sh *
 80K	AdjustedClose.d
 80K	Close.d
 40K	DataSource.d
 16K	DataSource.k
 80K	DataSource.v
 80K	Date.d
 40K	Exchange.d
 16K	Exchange.k
 80K	Exchange.v
 80K	High.d
 80K	Low.d
 80K	Open.d
 40K	Ticker.d
 64K	Ticker.k
 64M	Ticker.v
 80K	Volume.d
 80K	timestamp.d
```

Please note the Ticker.v file taking up 65M. the rest are all small.

**Comment by puzpuzpuz** [comment] 2023-01-05 08:20
@Roh-codeur it looks like you have indexes on `DataSource`, `Exchange` and `Ticker` columns. Is that correct? The DDL you've shared doesn't include indexes, so that's why I'm asking. Could you try dropping the indexes and check the disk space after that? https://questdb.io/docs/reference/sql/alter-table-alter-column-drop-index/

**Comment by Roh-codeur** [comment] 2023-01-05 10:39
@puzpuzpuz @ideoma my sincerest apologies to you both. You are right, I did indeed have indices, I was looking to remove them to check the disk usage impact. I will drop and report back. 

qq: do we expect indices to have a significant impact. 
Also, i will try out without indices - do we expect the query performance to remain the same?

**Comment by Roh-codeur** [comment] 2023-01-05 11:35
> It seems that the `Ticker` column has unique or almost unique values, i.e. the values are not repeated between the rows or are repeated in a few rows per partition only. Could you confirm that it's the case? If so, the index size will be large since we reserve at least 256 row id slots (2KB) per each symbol column value in the index file. This parameter is exposed as the [index capacity](https://questdb.io/docs/concept/indexes/#index-capacity) which is 256 by default.

Correct, I only have data for about 2000 tickers. I will play around with different values of index capacity. If you have any ideas, please do let me know 

> That highly depends on the queries you're running, but in many cases our parallel filter framework goes on par or better than index-based execution plans.

Got it, I have noticed the same. I will give it a shot on this table as well. 

Thanks!

**Comment by ideoma** [comment] 2023-01-12 21:12
I'm closing the issue.

Here is the documentation about index capacity

https://questdb.io/docs/concept/indexes/#index-capacity

**Closed by ideoma** 2023-01-12 21:12 UTC

**Comment by Roh-codeur** [comment] 2023-01-15 13:26
@ideoma @puzpuzpuz: my apologies for the delay in posting, I was traveling.  I am afraid, regarding this issue, I am still at a loss. 

I have the below table and it uses 117M of disk space! 

```sql
CREATE TABLE exchange_holidays(
        Exchange SYMBOL CAPACITY 50,
        DataSource SYMBOL CAPACITY 50,
        Date TIMESTAMP,
        Holiday STRING, 
        type SYMBOL CAPACITY 10,
        timestamp TIMESTAMP)
TIMESTAMP(Date)
PARTITION BY MONTH;
```

```sql
select count(*) from 'exchange_holidays';

89 rows
```

```bash
du -sh *
 16K	_tab_index.d
4.0K	_upgrade.d
117M	exchange_holidays     ------> Please note
  0B	exchange_holidays.lock
2.2M	sys.column_versions_purge_log
  0B	sys.column_versions_purge_log.lock
4.3M	sys.text_import_log
  0B	sys.text_import_log.lock
 47M	telemetry
  0B	telemetry.lock
 80M	telemetry_config
  0B	telemetry_config.lock
```

```
cd exchange_holidays/
du -sh *
 28K	2000-01
 28K	2000-04
 28K	2001-01
 28K	2001-04
 28K	2002-01
 28K	2002-03
..... (all dirs 28K)
112K	2010-04
 28K	2011-01
(... truncated output, all dirs 28K)
 28K	2022-11
 28K	2023-01
112M	2023-04. ---> Please note this directory
 16K	DataSource.c
 16K	DataSource.k
 16K	DataSource.o
1.0M	DataSource.v
 16K	Exchange.c
 16K	Exchange.k
 16K	Exchange.o
1.0M	Exchange.v
 16K	_cv
 16K	_meta
 16K	_todo_
 16K	_txn
 36K	_txn_scoreboard
 16K	type.c
 16K	type.k
 16K	type.o
1.0M	type.v

```

``` sql
select count(*) from 'exchange_holidays' where date >= '2023';

3 rows
```

so, I am afraid I am a bit confused, how is the directory which pertains to a partition which has 3 rows, taking up 112M! 

thanks a lot for your help in sorting this out. my apologies if I missed out something obvious, I am still going through  QuestDB docs. 

ta!
Roh

**Comment by Roh-codeur** [comment] 2023-01-15 13:31
@puzpuzpuz @ideoma 
hmm.. so, while I wrote the above post and went back to my directory, I noticed the below

```
du -sh *
 16K	_tab_index.d
4.0K	_upgrade.d
2.2M	exchange_holidays.  ----> its now taking up 2.2M. and the .lock dir is gone. 
2.2M	sys.column_versions_purge_log
  0B	sys.column_versions_purge_log.lock
4.3M	sys.text_import_log
  0B	sys.text_import_log.lock
 47M	telemetry
  0B	telemetry.lock
 80M	telemetry_config
  0B	telemetry_config.lock
```

looks like Questdb was doing something and taking up disk space.

**Comment by puzpuzpuz** [comment] 2023-01-15 13:34
If you're writing O3 data, the database may retain old partition versions. Once there are no readers reading these older partitions, their directories get deleted.

Also, if you want even lower table size, try setting `cairo.writer.data.append.page.size` [engine setting](https://questdb.io/docs/reference/configuration/#cairo-engine) to a lower value, say, `1M`. Its default value is `16M` which means that the engine uses at least 16MB for any column file even it has a single row. This setting is also used when a column file needs to grow.

**Comment by Roh-codeur** [comment] 2023-01-15 14:04
@puzpuzpuz 
> If you're writing O3 data, the database may retain old partition versions. Once there are no readers reading these older partitions, their directories get deleted.

I dropped the table, and checked that the directory had gone away before re-inserting the rows.

> Also, if you want even lower table size, try setting `cairo.writer.data.append.page.size` [engine setting](https://questdb.io/docs/reference/configuration/#cairo-engine) to a lower value, say, `1M`. Its default value is `16M` which means that the engine uses at least 16MB for any column file even it has a single row. This setting is also used when a column file needs to grow.

ahh! thanks a lot for this pointer. I will play around with this. 

thanks, guys, you have been amazing - the product and the support, I am so impressed!

**Comment by Roh-codeur** [comment] 2023-01-17 11:49
@puzpuzpuz Sorry to bother again, last question on this please

Do we know why the initial disk usage is somewhat larger and what causes the disk usage to drop significantly. Could this be related to how I am inserting rows? I am using the official python lib to insert rows

Thanks

**Comment by puzpuzpuz** [comment] 2023-01-17 13:43
> Could this be related to how I am inserting rows? I am using the official python lib to insert rows

Yes, it's very likely to be caused by out-of-order (O3) writes. See my update on #2831.
