### ISSUE TITLE
Optimizing "order by timestamp desc limit k" queries

### ISSUE THREAD

**Issue by mounte** [questdb/questdb#3412] opened 2023-05-26 16:19 UTC
### Is your feature request related to a problem?

With regular sql-background knowledge in an attempt to get the most recent k number of samples we posed queries like:
```
SELECT ... FROM ... WHERE ...
ORDER BY timestamp DESC
LIMIT 10
```
The query works but actually scans through (mmap logs) most/all of the table data and would from time to time respond super slow.

After discussing with @ideoma on slack it was obvious that this case alread us solved by simply using:
```
SELECT ... FROM ... WHERE ...
LIMIT -10
```
Which performs much better.

### Describe the solution you'd like.

1) Document the use-case
* If you want to select the k most recent samples do this...

2) Automatically pick up on this query pattern and transpose it to the more efficent one internal in the query engine.

Attaching the query plans for the two cases
First the "order by timestamp desc limit"
![order_by_2023-05-26_18-01](https://github.com/questdb/questdb/assets/131137/a93462ce-845c-4254-a6ae-6cf2950e4aaa)

Followed by the better performing alternative:
![neg_limit_2023-05-26_18-00](https://github.com/questdb/questdb/assets/131137/bdd53e78-fa58-449c-9f42-9085cc21cb12)

**Comment by bziobrowski** [comment] 2023-05-29 07:13
I can't reproduce the issue on demo site and get same good execution plan for : 

```sql
EXPLAIN
SELECT *
FROM trips 
where vendor_id = 'CMT'
ORDER BY pickup_datetime DESC
LIMIT 10
```
and 
```sql
EXPLAIN
SELECT *
FROM trips 
where vendor_id = 'CMT'
LIMIT -10
```
 
Please share table schema and query text to allow us to reproduce the issue .

**Comment by mounte** [comment] 2023-05-29 07:19
```
explain select * from mock_plc order by timestamp desc limit 10
```
vs
```
explain select * from mock_plc limit -10
```
[table_structure.csv](https://github.com/questdb/questdb/files/11589450/table_structure.csv)

**Comment by bziobrowski** [comment] 2023-05-29 07:26
Could you share table DDL ? 
You can get it from web console if you right-click on table and choose "copy schema to clipboard" .

**Comment by mounte** [comment] 2023-05-29 07:31
`CREATE TABLE 'mock_plc' (
  header_tick LONG,
  header_timestamp LONG,
  header_timestamp_ms LONG,
  motion_set_tcp_x DOUBLE,
  motion_set_tcp_y DOUBLE,
  motion_set_tcp_z DOUBLE,
  motion_set_tcp_a DOUBLE,
  motion_set_tcp_b DOUBLE,
  motion_set_tcp_c DOUBLE,
  motion_set_tcp_u DOUBLE,
  motion_set_joint_q1 DOUBLE,
  motion_set_joint_q2 DOUBLE,
  motion_set_joint_q3 DOUBLE,
  motion_set_joint_q4 DOUBLE,
  motion_set_joint_q5 DOUBLE,
  motion_set_joint_q6 DOUBLE,
  motion_set_joint_q7 DOUBLE,
  motion_actual_tcp_x DOUBLE,
  motion_actual_tcp_y DOUBLE,
  motion_actual_tcp_z DOUBLE,
  motion_actual_tcp_a DOUBLE,
  motion_actual_tcp_b DOUBLE,
  motion_actual_tcp_c DOUBLE,
  motion_actual_tcp_u DOUBLE,
  motion_actual_joint_q1 DOUBLE,
  motion_actual_joint_q2 DOUBLE,
  motion_actual_joint_q3 DOUBLE,
  motion_actual_joint_q4 DOUBLE,
  motion_actual_joint_q5 DOUBLE,
  motion_actual_joint_q6 DOUBLE,
  motion_actual_joint_q7 DOUBLE,
  motion_lookahead_tcp_x DOUBLE,
  motion_lookahead_tcp_y DOUBLE,
  motion_lookahead_tcp_z DOUBLE,
  motion_lookahead_tcp_a DOUBLE,
  motion_lookahead_tcp_b DOUBLE,
  motion_lookahead_tcp_c DOUBLE,
  motion_lookahead_tcp_u DOUBLE,
  motion_lookahead_joint_q1 DOUBLE,
  motion_lookahead_joint_q2 DOUBLE,
  motion_lookahead_joint_q3 DOUBLE,
  motion_lookahead_joint_q4 DOUBLE,
  motion_lookahead_joint_q5 DOUBLE,
  motion_lookahead_joint_q6 DOUBLE,
  motion_lookahead_joint_q7 DOUBLE,
  motion_activeCompensation BOOLEAN,
  swath_SwathBusy BOOLEAN,
  swath_SwathNumber LONG,
  feedrate_programmed DOUBLE,
  feedrate_overridePercent DOUBLE,
  feedrate_effective DOUBLE,
  feedrate_actual DOUBLE,
  metrologyEstimateTcp_x DOUBLE,
  metrologyEstimateTcp_y DOUBLE,
  metrologyEstimateTcp_z DOUBLE,
  metrologyEstimateTcp_a DOUBLE,
  metrologyEstimateTcp_bI DOUBLE,
  metrologyEstimateTcp_cJ DOUBLE,
  metrologyEstimateTcp_dK DOUBLE,
  metrologyEstimateTcp_u DOUBLE,
  metrologyErrorTcp_x DOUBLE,
  metrologyErrorTcp_y DOUBLE,
  metrologyErrorTcp_z DOUBLE,
  metrologyErrorTcp_a DOUBLE,
  metrologyErrorTcp_b DOUBLE,
  metrologyErrorTcp_c DOUBLE,
  metrologyErrorTcp_u DOUBLE,
  motion_revision LONG,
  BL2U_By DOUBLE,
  BL3U_By DOUBLE,
  BL2L_By DOUBLE,
  BL3L_By DOUBLE,
  BL2U_Ba DOUBLE,
  BL3U_Ba DOUBLE,
  BL2L_Ba DOUBLE,
  BL3L_Ba DOUBLE,
  BL1_M1U_Pz DOUBLE,
  BL1_M1U_Pa DOUBLE,
  BL1_M1U_Pb DOUBLE,
  BL1_M1U_P1_Pb DOUBLE,
  BL1_M2U_Pz DOUBLE,
  BL1_M2U_Pa DOUBLE,
  BL1_M2U_Pb DOUBLE,
  BL1_M2U_P1_Pb DOUBLE,
  BL1_M3U_Pz DOUBLE,
  BL1_M3U_Pa DOUBLE,
  BL1_M3U_Pb DOUBLE,
  BL1_M3U_P1_Pb DOUBLE,
  BL1_M1L_Pz DOUBLE,
  BL1_M1L_Pa DOUBLE,
  BL1_M1L_Pb DOUBLE,
  BL1_M1L_P1_Pb DOUBLE,
  BL1_M2L_Pz DOUBLE,
  BL1_M2L_Pa DOUBLE,
  BL1_M2L_Pb DOUBLE,
  BL1_M2L_P1_Pb DOUBLE,
  BL1_M3L_Pz DOUBLE,
  BL1_M3L_Pa DOUBLE,
  BL1_M3L_Pb DOUBLE,
  BL1_M3L_P1_Pb DOUBLE,
  BL2U_M1_Pz DOUBLE,
  BL2U_M1_Pa DOUBLE,
  BL2U_M1_Pb DOUBLE,
  BL2U_M1_P1_Pb DOUBLE,
  BL2U_M2_Pz DOUBLE,
  BL2U_M2_Pa DOUBLE,
  BL2U_M2_Pb DOUBLE,
  BL2U_M2_P1_Pb DOUBLE,
  BL3U_M1_Pz DOUBLE,
  BL3U_M1_Pa DOUBLE,
  BL3U_M1_Pb DOUBLE,
  BL3U_M1_P1_Pb DOUBLE,
  BL3U_M2_Pz DOUBLE,
  BL3U_M2_Pa DOUBLE,
  BL3U_M2_Pb DOUBLE,
  BL3U_M2_P1_Pb DOUBLE,
  BL2L_M1_Pz DOUBLE,
  BL2L_M1_Pa DOUBLE,
  BL2L_M1_Pb DOUBLE,
  BL2L_M1_P1_Pb DOUBLE,
  BL2L_M2_Pz DOUBLE,
  BL2L_M2_Pa DOUBLE,
  BL2L_M2_Pb DOUBLE,
  BL2L_M2_P1_Pb DOUBLE,
  BL3L_M1_Pz DOUBLE,
  BL3L_M1_Pa DOUBLE,
  BL3L_M1_Pb DOUBLE,
  BL3L_M1_P1_Pb DOUBLE,
  BL3L_M2_Pz DOUBLE,
  BL3L_M2_Pa DOUBLE,
  BL3L_M2_Pb DOUBLE,
  BL3L_M2_P1_Pb DOUBLE,
  BL1_CM1_CMz DOUBLE,
  BL1_CM2_CMz DOUBLE,
  BL2U_CM1_CMz DOUBLE,
  BL2U_CM2_CMz DOUBLE,
  BL3U_CM1_CMz DOUBLE,
  BL3U_CM2_CMz DOUBLE,
  BL2L_CM1_CMz DOUBLE,
  BL2L_CM2_CMz DOUBLE,
  BL3L_CM1_CMz DOUBLE,
  BL3L_CM2_CMz DOUBLE,
  hw_revision LONG,
  BL1_Dz1 DOUBLE,
  BL1_Dz2 DOUBLE,
  BL1_Dz3 DOUBLE,
  BL1_Dz4 DOUBLE,
  BL1_Dz5 DOUBLE,
  BL1_Dz6 DOUBLE,
  BL2L_Dz1 DOUBLE,
  BL2L_Dz2 DOUBLE,
  BL2L_Dz3 DOUBLE,
  BL3L_Dz1 DOUBLE,
  BL3L_Dz2 DOUBLE,
  BL3L_Dz3 DOUBLE,
  BL2U_Dz1 DOUBLE,
  BL2U_Dz2 DOUBLE,
  BL2U_Dz3 DOUBLE,
  BL3U_Dz1 DOUBLE,
  BL3U_Dz2 DOUBLE,
  BL3U_Dz3 DOUBLE,
  BL2L_Dx1 DOUBLE,
  BL2L_Dx2 DOUBLE,
  BL2L_Dx3 DOUBLE,
  BL3L_Dx1 DOUBLE,
  BL3L_Dx2 DOUBLE,
  BL3L_Dx3 DOUBLE,
  BL2U_Dx1 DOUBLE,
  BL2U_Dx2 DOUBLE,
  BL2U_Dx3 DOUBLE,
  BL3U_Dx1 DOUBLE,
  BL3U_Dx2 DOUBLE,
  BL3U_Dx3 DOUBLE,
  BL1_Acc_X DOUBLE,
  BL1_Acc_Y DOUBLE,
  BL1_Acc_Z DOUBLE,
  BL2L_Acc_X DOUBLE,
  BL2L_Acc_Y DOUBLE,
  BL2L_Acc_Z DOUBLE,
  BL3L_Acc_X DOUBLE,
  BL3L_Acc_Y DOUBLE,
  BL3L_Acc_Z DOUBLE,
  BL2U_Acc_X DOUBLE,
  BL2U_Acc_Y DOUBLE,
  BL2U_Acc_Z DOUBLE,
  BL3U_Acc_X DOUBLE,
  BL3U_Acc_Y DOUBLE,
  BL3U_Acc_Z DOUBLE,
  BL2L_O_x DOUBLE,
  BL2L_O_y DOUBLE,
  BL2L_O_z DOUBLE,
  BL2L_O_a DOUBLE,
  BL2L_O_bI DOUBLE,
  BL2L_O_cJ DOUBLE,
  BL2L_O_dK DOUBLE,
  BL2L_O_u DOUBLE,
  BL3L_O_x DOUBLE,
  BL3L_O_y DOUBLE,
  BL3L_O_z DOUBLE,
  BL3L_O_a DOUBLE,
  BL3L_O_bI DOUBLE,
  BL3L_O_cJ DOUBLE,
  BL3L_O_dK DOUBLE,
  BL3L_O_u DOUBLE,
  BL2U_O_x DOUBLE,
  BL2U_O_y DOUBLE,
  BL2U_O_z DOUBLE,
  BL2U_O_a DOUBLE,
  BL2U_O_bI DOUBLE,
  BL2U_O_cJ DOUBLE,
  BL2U_O_dK DOUBLE,
  BL2U_O_u DOUBLE,
  BL3U_O_x DOUBLE,
  BL3U_O_y DOUBLE,
  BL3U_O_z DOUBLE,
  BL3U_O_a DOUBLE,
  BL3U_O_bI DOUBLE,
  BL3U_O_cJ DOUBLE,
  BL3U_O_dK DOUBLE,
  BL3U_O_u DOUBLE,
  BL1_O_x DOUBLE,
  BL1_O_y DOUBLE,
  BL1_O_z DOUBLE,
  BL1_O_a DOUBLE,
  BL1_O_bI DOUBLE,
  BL1_O_cJ DOUBLE,
  BL1_O_dK DOUBLE,
  BL1_O_u DOUBLE,
  BL1_EC_x DOUBLE,
  BL1_EC_y DOUBLE,
  BL1_EC_z DOUBLE,
  BL1_EC_a DOUBLE,
  BL1_EC_bI DOUBLE,
  BL1_EC_cJ DOUBLE,
  BL1_EC_dK DOUBLE,
  BL1_EC_u DOUBLE,
  BL1_IMU_X DOUBLE,
  BL1_IMU_Y DOUBLE,
  BL1_IMU_Z DOUBLE,
  BL2L_EC_x DOUBLE,
  BL2L_EC_y DOUBLE,
  BL2L_EC_z DOUBLE,
  BL2L_EC_a DOUBLE,
  BL2L_EC_bI DOUBLE,
  BL2L_EC_cJ DOUBLE,
  BL2L_EC_dK DOUBLE,
  BL2L_EC_u DOUBLE,
  BL3L_EC_x DOUBLE,
  BL3L_EC_y DOUBLE,
  BL3L_EC_z DOUBLE,
  BL3L_EC_a DOUBLE,
  BL3L_EC_bI DOUBLE,
  BL3L_EC_cJ DOUBLE,
  BL3L_EC_dK DOUBLE,
  BL3L_EC_u DOUBLE,
  BL2U_EC_x DOUBLE,
  BL2U_EC_y DOUBLE,
  BL2U_EC_z DOUBLE,
  BL2U_EC_a DOUBLE,
  BL2U_EC_bI DOUBLE,
  BL2U_EC_cJ DOUBLE,
  BL2U_EC_dK DOUBLE,
  BL2U_EC_u DOUBLE,
  BL3U_EC_x DOUBLE,
  BL3U_EC_y DOUBLE,
  BL3U_EC_z DOUBLE,
  BL3U_EC_a DOUBLE,
  BL3U_EC_bI DOUBLE,
  BL3U_EC_cJ DOUBLE,
  BL3U_EC_dK DOUBLE,
  BL3U_EC_u DOUBLE,
  BL2U_By_Enc DOUBLE,
  BL3U_By_Enc DOUBLE,
  BL2L_By_Enc DOUBLE,
  BL3L_By_Enc DOUBLE,
  BL2U_Ba_Enc DOUBLE,
  BL3U_Ba_Enc DOUBLE,
  BL2L_Ba_Enc DOUBLE,
  BL3L_Ba_Enc DOUBLE,
  BL1_CM1_Enc DOUBLE,
  BL1_CM2_Enc DOUBLE,
  BL2U_CM1_Enc DOUBLE,
  BL2U_CM2_Enc DOUBLE,
  BL3U_CM1_Enc DOUBLE,
  BL3U_CM2_Enc DOUBLE,
  BL2L_CM1_Enc DOUBLE,
  BL2L_CM2_Enc DOUBLE,
  BL3L_CM1_Enc DOUBLE,
  BL3L_CM2_Enc DOUBLE,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY DAY;`

**Comment by bziobrowski** [comment] 2023-05-29 08:14
I get the same plans as above on 7.1.3 .
Are you sure issue affects the version and there's nothing missing in the sql ? 
In issue description you mentioned WHERE clause .

**Comment by bziobrowski** [comment] 2023-05-29 08:51
Closing issue because it can't be reproduced.

**Closed** 2023-05-29 08:51 UTC
Labels: New feature
