### ISSUE TITLE
LineTcpConnectionContext [4372] could not process line data

### ISSUE THREAD

**Issue by xinyuyy** [questdb/questdb#2856] opened 2022-12-10 00:32 UTC
### Describe the bug

2022-12-09T11:06:14.735369Z I tcp-line-server connected [ip=127.0.0.1, fd=4372]
2022-12-09T11:06:14.735440Z E i.q.c.l.t.LineTcpConnectionContext [4372] could not process line data [table=dev_temp_his, msg=writer is in error, aborting ILP pipeline, errno=0]
2022-12-09T11:06:14.735450Z E i.q.c.l.t.LineTcpConnectionContext [4372] could not parse measurement, NONE at 430, line (may be mangled due to partial parsing): 'dev_temp_his,dev_id=60111459 id=0i,imei="866469054692918",sim="89861120207014654706",iot_dev="",temp=23.62,shidu=19.45,qos=22i,back_water_temp=0,in_water_temp=0,pa=0,uptime="",temp_currect=0,dis_mode="",total=0i,temp_over="",temp_high=0,temp_low=0,alarm_time="",msg_type="",prej_ver="14",hard_ver="",sfw_ver="",pro_ver="",productId=15008180i,deviceID="57f01d7d9d51421689c27ef6975ac50b",groupId=0i,battery=3180i 1670612774734419000'
2022-12-09T11:06:14.735455Z I tcp-line-server scheduling disconnect [fd=4372, reason=0]

### Expected Behavior

After running normally for a period of time, an error occurred.

### Environment

```markdown
- **QuestDB version**:6.5.2
- **OS**:windows server 2019 datacenter
- **Browser**:
```

**Comment by pswu11** [comment] 2022-12-12 14:26
Hi @xinyuyy thanks for reporting the issue! Could you try out the latest version and see if the same problem still occurs?

**Comment by glasstiger** [comment] 2022-12-12 14:37
Hi @xinyuyy, upgrading to the latest version is definitely something you should try.
If it happens again, please, look for errors in the log before the line you included in the issue description.
The `msg=writer is in error` bit tells me that there must have been some kind of problem before this, probably some kind of failure during a commit.

**Comment by glasstiger** [comment] 2022-12-23 13:12
Hi @xinyuyy, could you let us know, please, if you still experience issues or the problem has been resolved?

**Comment by puzpuzpuz** [comment] 2023-01-04 09:48
@xinyuyy could you tell us if the issue is still actual on the latest version?

**Comment by glasstiger** [comment] 2023-01-26 10:23
Hi @xinyuyy,
closing this issue now but feel free to comment on it or create a new one if you still have problems.

**Closed by glasstiger** 2023-01-26 10:23 UTC
Labels: Bug, ILP
