### ISSUE TITLE
High Resilience | Offline First Replication Mode

### ISSUE THREAD

**Issue by sirinath** [questdb/questdb#196] opened 2020-04-21 06:16 UTC
Through QuestDB is still not distributed but when building replication and other distributed feature add an option for offline 1st  replication mode where nodes may be offline for short or extended periods of time.

The offline 1st mode may be slower if this is the case if this is not relevant this should be an option not to use it.

E.g.:

- https://orbitdb.org/
- https://couchdb.apache.org/
- https://www.couchbase.com/
- https://riak.com/products/

**Comment by bsmth** [comment] 2021-03-19 09:22
I'm closing this as it seems to be a duplicate of https://github.com/questdb/questdb/issues/166.

If you think I have closed this by mistake, feel free to reopen with a more details. :)

Thank you!

**Closed by bsmth** 2021-03-19 09:22 UTC
Labels: New feature
