### ISSUE TITLE
lag() function

### ISSUE THREAD

**Issue by Luyang2902** [questdb/questdb#2468] opened 2022-08-26 10:07 UTC
### Is your feature request related to a problem?

lag() function is useful when calculate the rolling spread of time series

**Comment by Zahlii** [comment] 2022-08-28 18:48
Duplicate of https://github.com/questdb/questdb/issues/1268 ?

**Comment by puzpuzpuz** [comment] 2022-08-29 06:33
Closing this one in favor of #1268

**Closed by puzpuzpuz** 2022-08-29 06:33 UTC
Labels: New feature, Good first issue
