### ISSUE TITLE
SQL JOIN MISMATCH

### ISSUE THREAD

**Issue by Sidopolis** [questdb/questdb#3200] opened 2023-04-16 15:13 UTC
### Describe the bug

Based on the information provided, it seems like there is a type mismatch error when joining two tables on an INT and a LONG column. The query is attempting to join the "x" column from a table generated using the "long_sequence" function, with the "y" column from a subquery that casts the "x" column to an INT.

The expected behavior is that the INT value in the subquery should be upcast to LONG and compared to the LONG value in the other table. This should result in the query returning 100 rows.

However, the current behavior is that an error is shown indicating a join column mismatch, which suggests that the query is not correctly handling the type conversion.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment] 2023-04-17 07:13
Duplicate of #1679

**Closed by bziobrowski** 2023-04-17 07:13 UTC
