### ISSUE TITLE
Flaky testParallelStressMultipleThreadsMultipleWorkersPositiveLimitJitDisabled

### ISSUE THREAD

**Issue by ideoma** [questdb/questdb#2607] opened 2022-10-07 13:13 UTC
### Describe the bug

Failed on Mac

```
2022-10-07T09:32:09.799733Z I i.q.c.AbstractCairoTest Starting test AsyncOffloadTest#testParallelStressMultipleThreadsMultipleWorkersPositiveLimitJitDisabled
2022-10-07T09:32:09.800887Z I i.q.c.m.EngineMigration upgrading database [version=426]
2022-10-07T09:32:09.800976Z I i.q.c.m.EngineMigration upgraded tables to 426
2022-10-07T09:32:09.802847Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.808897Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.813815Z I i.q.c.CairoEngine locked [table=`__syscolumn_versions_purge_log`, thread=184]
2022-10-07T09:32:09.818579Z I i.q.c.p.WriterPool created [table=`__syscolumn_versions_purge_log`, thread=184]
2022-10-07T09:32:09.818636Z I i.q.c.TableWriter open '__syscolumn_versions_purge_log'
2022-10-07T09:32:09.820972Z I i.q.c.TableWriter purging non attached partitions [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit8418217049669055840/dbRoot/__syscolumn_versions_purge_log]
2022-10-07T09:32:09.821221Z I i.q.c.CairoEngine unlocked [table=`__syscolumn_versions_purge_log`]
2022-10-07T09:32:09.821259Z I i.q.c.p.WriterPool >> [table=`__syscolumn_versions_purge_log`, thread=184]
2022-10-07T09:32:09.821471Z I i.q.c.p.ReaderPool open '__syscolumn_versions_purge_log' [at=0:0]
2022-10-07T09:32:09.822617Z I i.q.g.SqlCompiler plan [q=`select-choose ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed from (select [ts, table_name, column_name, table_id, truncate_version, columnType, table_partition_by, updated_txn, column_version, partition_timestamp, partition_name_txn, completed] from __syscolumn_versions_purge_log timestamp (ts) where completed = null)`, fd=-1]
2022-10-07T09:32:09.823843Z I i.q.c.AbstractCairoTest os scheduled worker started [name=questdb-worker-11]
2022-10-07T09:32:09.823967Z I i.q.c.AbstractCairoTest os scheduled worker started [name=questdb-worker-12]
2022-10-07T09:32:09.824177Z I i.q.c.AbstractCairoTest os scheduled worker started [name=questdb-worker-13]
2022-10-07T09:32:09.824232Z I i.q.c.AbstractCairoTest worker pool started [pool=worker]
2022-10-07T09:32:09.824305Z I i.q.c.AbstractCairoTest os scheduled worker started [name=questdb-worker-14]
2022-10-07T09:32:09.824549Z I i.q.c.CairoEngine locked [table=`x`, thread=184]
2022-10-07T09:32:09.827822Z I i.q.c.p.WriterPool created [table=`x`, thread=184]
2022-10-07T09:32:09.827888Z I i.q.c.TableWriter open 'x'
2022-10-07T09:32:09.830314Z I i.q.c.TableWriter switched partition [path='/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit8418217049669055840/dbRoot/x/default']
2022-10-07T09:32:09.830498Z I i.q.c.CairoEngine unlocked [table=`x`]
2022-10-07T09:32:09.830815Z I i.q.c.p.WriterPool >> [table=`x`, thread=184]
2022-10-07T09:32:09.831596Z I i.q.c.p.WriterPool << [table=`x`, thread=184]
2022-10-07T09:32:09.833424Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.838191Z I i.q.c.p.ReaderPool open 'x' [at=0:0]
2022-10-07T09:32:09.839017Z I i.q.g.SqlCompiler plan [q=`select-choose v from (select [v] from x where v > 3326086085493629941L and v < 4326086085493629941L) limit 10`, fd=-1]
2022-10-07T09:32:09.841934Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.847829Z I i.q.g.SqlCompiler plan [q=`select-choose v from (select [v] from x where v > 3326086085493629941L and v < 4326086085493629941L) limit 10`, fd=-1]
2022-10-07T09:32:09.851306Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.855725Z I i.q.g.SqlCompiler plan [q=`select-choose v from (select [v] from x where v > 3326086085493629941L and v < 4326086085493629941L) limit 10`, fd=-1]
2022-10-07T09:32:09.857646Z I i.q.g.FunctionFactoryCache loading functions [test=true]
2022-10-07T09:32:09.883815Z I i.q.g.SqlCompiler plan [q=`select-choose v from (select [v] from x where v > 3326086085493629941L and v < 4326086085493629941L) limit 10`, fd=-1]
java.lang.AssertionError: expected:<v
3394168647660478011
4086802474270249591
3958193676455060057
3619114107112892010
3705833798044144433
4238042693748641409
3518554007419864093
4014104627539596639
3393210801760647293
4099611147050818391
> but was:<v
3394168647660478011
4086802474270249591
3958193676455060057
3619114107112892010
3705833798044144433
4238042693748641409
3518554007419864093
4014104627539596639
3393210801760647293
4290477379978201771
>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:341)
	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:319)
	at io.questdb.griffin.AbstractGriffinTest.assertCursor(AbstractGriffinTest.java:157)
	at io.questdb.griffin.AsyncOffloadTest.assertCursor(AsyncOffloadTest.java:265)2022-10-07T09:32:09.884820Z I i.q.c.p.ReaderPool open 'x' [at=0:1]

```

https://dev.azure.com/questdb/questdb/_build/results?buildId=10844&view=logs&j=4955d095-2078-5b5d-31a1-99f71a7c612c&t=e558e7bf-9ebf-5c2e-7d87-eed2e40883cb

**Comment by puzpuzpuz** [comment] 2022-10-07 18:22
Tried running this test on my Linux x86-64 machine for 20+ minutes with periodically running `stress-ng` to consume all cores except one, but the flakiness didn't show up. Would be nice if someone with MacOS could also try.

**Comment by pivovarit** [comment] 2022-10-11 18:53
Ran it in a loop and forgot about it. 15k repetitions later and still going...

> MacOS with 2,3 GHz 8-Core Intel Core i9

**Comment by bluestreak01** [comment] 2022-10-18 17:10
duplicate of https://github.com/questdb/questdb/issues/2513

**Closed** 2022-10-18 17:11 UTC
Labels: Schrödinger's bug
