### ISSUE TITLE
Geospatial data types and functions

### ISSUE THREAD

**Issue by igor-suhorukov** [questdb/questdb#491] opened 2020-07-07 14:29 UTC
**Is your feature request related to a problem? Please describe.**
There are plenty number of time series data that contains geo location, for example telecom, transport, aerospace.
QuestDB must have data structures like location, paths and so on... 

**Describe the solution you'd like**
PostGIS compatible data serialization format should help integrate into existing vizualization solution and GIS applications like QGIS.

**Describe alternatives you've considered**

**Additional context**
It is easy to load OSM data into PostGIS and visualize query in QGIS:
![Screenshot from 2020-07-07 17-22-17](https://user-images.githubusercontent.com/10332206/86795638-7207a900-c076-11ea-9223-9018e84797b4.png)
As end user I expect easy data loading/transformation process, existing "how to" instruction and simple data visualization in existing desktop/online tools.

[The multilayer temporal network of public transport in Great Britain](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4412150/)
[A collection of public transport network data sets for 25 cities](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5952869/)

**Comment by mpsq** [comment] 2020-10-13 10:37
Closing, this is a duplicate of #343

**Closed by mpsq** 2020-10-13 10:37 UTC
Labels: New feature, SQL
