### ISSUE TITLE
ISSUE WITH TIMEZONE

### ISSUE THREAD

**Issue by vishwajeet5** [questdb/questdb#3224] opened 2023-04-18 08:07 UTC
### Is your feature request related to a problem?

Quest DB currently does not support time zone conversions.
Which can cause issues when working with data across different time zones.

### Describe the solution you'd like.

I read that the --date argument when adding a commit can be used to specify the timestamp and the time Zone offset. I'm curious if there's a way to globally set just the time Zone offset so it matches my time, Zone. I'm in EST which is -0500 from UTC, and whenever I commit and push to GitHub my contributions never shows up on the correct day. IE. it's 2:00 AM where I am but git sets the time Zone offset to UTC. Now when I commit/push my changes to GitHub they will show up as 9 PM UTC.

**Comment by bziobrowski** [comment] 2023-04-18 08:07
Duplicate of https://github.com/questdb/questdb/issues/3218 . Please look at the answer I gave there .

**Comment by vishwajeet5** [comment] 2023-04-18 08:14
i dont think

**Comment by bziobrowski** [comment] 2023-04-18 08:18
You're right the first  text is a copy of that issue while second is a copy & paste of https://stackoverflow.com/questions/26375318/how-can-i-change-my-git-timezone-offset, which is completely unrelated to QuestDB .

**Closed** 2023-04-18 08:17 UTC
Labels: New feature
