### ISSUE TITLE
Cannot insert row in a table

### ISSUE THREAD

**Issue by micheleBridi** [questdb/questdb#3377] opened 2023-05-22 10:30 UTC
### Describe the bug

I have two identical applications that run on two different computers and insert data on questDB(7.1.1) via ILP. No data has been entered on a PC for two days. I tried to enter some data manually but they are still not entered.

![image](https://github.com/questdb/questdb/assets/74403751/927ffd41-9d7e-4614-9983-475db68c547f)

Checking the logs I found these errors, but nothing related to the Beams table:

2023-05-22T10:19:03.703194Z E i.q.c.w.WalPurgeJob could not delete directory [path=E:\QuestDB\db\Lots~3\wal17, errno=5]
2023-05-22T10:19:03.705895Z E i.q.c.w.WalPurgeJob could not delete directory [path=E:\QuestDB\db\AlarmHistory~6\wal564, errno=5]

### Environment

```markdown
- **QuestDB version**:7.1.1
- **OS**:Windows 10 Enterprise LTSC
- **Browser**: Chrome
```

**Comment by ideoma** [comment] 2023-05-22 10:35
This looks similar to
 
https://github.com/questdb/questdb/issues/3372

Can you run `select * from wal_tables()` to see what SeqTxn and WriterTxn are?
Did your Windows box ungracefully restart after the automatic update?

**Comment by micheleBridi** [comment] 2023-05-22 10:47
![image](https://github.com/questdb/questdb/assets/74403751/8fb5aa11-fe2c-48e0-a54d-1ba385e025e2)

Windows update are disabled.

**Comment by bziobrowski** [comment] 2023-05-23 15:23
The issue was seemingly caused by ungraceful restart and addressed by upgrading to 7.1.3 and enabling synchronous write mode via :  
cairo.commit.mode=sync
setting in server.conf .

**Closed by bziobrowski** 2023-05-23 15:23 UTC

**Comment by bodilove** [comment] 2023-09-28 06:45
My table 'ProcessRecord' suspended is equal to true and update data cannot be inserted. How to solve it?

![image](https://github.com/questdb/questdb/assets/26559417/571092e4-0a33-48b7-b2a6-b375ce69d78a)

**Comment by puzpuzpuz** [comment] 2023-09-28 06:47
@bodilove you should use ALTER TABLE RESUME WAL statement:
https://questdb.io/docs/reference/sql/alter-table-resume-wal/

**Comment by puzpuzpuz** [comment] 2023-09-28 06:48
Also, a table only gets suspended if a critical error has happened, so it's worth checking that.

**Comment by bodilove** [comment] 2023-09-28 06:59
Is it correct to execute this statement? The execution has been waiting. Do I need to wait directly?
![image](https://github.com/questdb/questdb/assets/26559417/85b0b8a7-40ae-4fc0-bdf3-3e371d098dae)

**Comment by bodilove** [comment] 2023-09-28 07:06
There is a large amount of data in the data table。

**Comment by puzpuzpuz** [comment] 2023-09-28 10:59
> The execution has been waiting. Do I need to wait directly?

Sorry, not sure if I understand. Once the statement returns, you should check `wal_tables()` and also server logs. The logs may contain some errors in case if the transaction from which you're resuming is problematic.

**Comment by bodilove** [comment] 2023-10-08 03:30
In my table ProcessRecord, the inserted data sequencerTxn number is changing, but the writerTxn has not changed, resulting in no data being queried. What is the reason?

![image](https://github.com/questdb/questdb/assets/26559417/bdd1d5b3-deb0-4c0a-a34a-002064d6145f)

**Comment by puzpuzpuz** [comment] 2023-10-08 06:07
@bodilove it could be a bug fixed in the recent release. Could you try 7.3.3?

**Comment by bodilove** [comment] 2023-10-10 00:09
> @bodilove it could be a bug fixed in the recent release. Could you try 7.3.3?

Okay, thank you, I'll try the upgraded version
