### ISSUE TITLE
Flaky AlterWalTableLineTcpReceiverTest.testAlterCommandTruncateTable()

### ISSUE THREAD

**Issue by nwoolmer** [questdb/questdb#4285] opened 2024-03-11 14:20 UTC
### To reproduce

CI build

https://dev.azure.com/questdb/questdb/_build/results?buildId=76981&view=ms.vss-test-web.build-test-results-tab&runId=276546&resultId=100686&paneView=debug

`[0] SymbolMap does not exist: C:\Users\VSSADM~1\AppData\Local\Temp\junit14626790240805956313\dbRoot\plug~2\room.o`

```
io.questdb.cairo.CairoException: [0] SymbolMap does not exist: C:\Users\VSSADM~1\AppData\Local\Temp\junit14626790240805956313\dbRoot\plug~2\room.o
	at io.questdb.cairo.CairoException.instance(CairoException.java:310)
	at io.questdb.cairo.CairoException.critical(CairoException.java:69)
	at io.questdb.cairo.SymbolMapReaderImpl.of(SymbolMapReaderImpl.java:150)
	at io.questdb.cairo.SymbolMapReaderImpl.<init>(SymbolMapReaderImpl.java:66)
	at io.questdb.cairo.TableReader.newSymbolMapReader(TableReader.java:816)
	at io.questdb.cairo.TableReader.openSymbolMaps(TableReader.java:933)
	at io.questdb.cairo.TableReader.<init>(TableReader.java:121)
	at io.questdb.cairo.pool.ReaderPool$R.<init>(ReaderPool.java:78)
	at io.questdb.cairo.pool.ReaderPool.newTenant(ReaderPool.java:55)
	at io.questdb.cairo.pool.ReaderPool.newTenant(ReaderPool.java:33)
	at io.questdb.cairo.pool.AbstractMultiTenantPool.get(AbstractMultiTenantPool.java:90)
	at io.questdb.cairo.CairoEngine.getReader(CairoEngine.java:522)
	at io.questdb.test.AbstractCairoTest.getReader(AbstractCairoTest.java:1234)
	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:252)
	at io.questdb.test.cutlass.line.tcp.AlterWalTableLineTcpReceiverTest.assertTable(AlterWalTableLineTcpReceiverTest.java:726)
	at io.questdb.test.cutlass.line.tcp.AlterWalTableLineTcpReceiverTest.lambda$testAlterCommandDropLastPartition$4(AlterWalTableLineTcpReceiverTest.java:193)
```

### QuestDB version:

7.3.11-SNAPSHOT

### OS, in case of Docker specify Docker and the Host OS:

windows-other

### File System, in case of Docker specify Host File System:

NTFS

### Full Name:

Nick Woolmer

### Affiliation:

QuestDB

### Have you followed Linux, MacOs kernel configuration steps to increase Maximum open files and Maximum virtual memory areas limit?

- [X] Yes, I have

**Comment by bluestreak01** [comment] 2024-10-21 12:08
duplicate of https://github.com/questdb/questdb/issues/4275

**Closed by bluestreak01** 2024-10-21 12:08 UTC
Labels: Schrödinger's bug
