### ISSUE TITLE
GORM2 connectivity issues

### ISSUE THREAD

**Issue by petrjahoda** [questdb/questdb#1021] opened 2021-05-15 07:55 UTC
**Describe the bug**
GORM has a new version 2,  for some time. Using postgres compatiblity approach from documentation does not work. GORM1 is working fine.

**To Reproduce**
Create a go file and run it.
```
package main

import (
	"fmt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

func main() {

	dsn := "host=localhost user=admin password=quest dbname=qdb port=8812 sslmode=disable"
	_, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err!=nil {
		fmt.Println(err.Error())
	}
}
```

When running you got response.
```
2021/05/15 09:51:28 /Users/petrjahoda/GolandProjects/questdb/main.go:12
[error] failed to initialize database, got error driver: bad connection
driver: bad connection

```

**Expected behavior**
Connection enabled.

**Screenshots**
This is the screenshot from console, questDB running in Docker.
<img width="778" alt="Screenshot 2021-05-15 at 9 52 52" src="https://user-images.githubusercontent.com/45359845/118352746-56f1a980-b563-11eb-8737-56e2ca116a88.png">

**Environment (please complete the following information):**
 - OS: macOS, but questDB run in Docker
 - Browser: not used
 - Version: 6.01.

**Comment by bsmth** [comment] 2021-09-14 12:12
Duplicate of https://github.com/questdb/questdb/issues/383

**Closed by bsmth** 2021-09-14 12:12 UTC
