### ISSUE TITLE
Flaky test: LineTcpReceiverTest.testRenameTable()

### ISSUE THREAD

**Issue by glasstiger** [questdb/questdb#3807] opened 2023-10-04 12:57 UTC
### Describe the bug

Intermittent test failure.
Exception in log:
```
2023-10-04T12:29:31.1318576Z java.lang.AssertionError: expected:<location	source	temp	timestamp
2023-10-04T12:29:31.1319580Z east5	sensor2	50.0	2016-06-13T17:43:50.100800Z
2023-10-04T12:29:31.1320599Z west6	sensor3	60.0	2016-06-13T17:43:50.100900Z
2023-10-04T12:29:31.1321323Z north	sensor4	70.0	2016-06-13T17:43:50.101000Z
2023-10-04T12:29:31.1321842Z > but was:<location	source	temp	timestamp
2023-10-04T12:29:31.1422190Z east5	sensor2	50.0	2016-06-13T17:43:50.100800Z
2023-10-04T12:29:31.1423270Z west6	sensor3	60.0	2016-06-13T17:43:50.100900Z
2023-10-04T12:29:31.1423569Z >
2023-10-04T12:29:31.1423841Z 	at org.junit.Assert.fail(Assert.java:89)
2023-10-04T12:29:31.1424180Z 	at org.junit.Assert.failNotEquals(Assert.java:835)
2023-10-04T12:29:31.1424622Z 	at org.junit.Assert.assertEquals(Assert.java:120)
2023-10-04T12:29:31.1425025Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:362)
2023-10-04T12:29:31.1425659Z 	at io.questdb.test.tools.TestUtils.assertEquals(TestUtils.java:345)
2023-10-04T12:29:31.1426071Z 	at io.questdb.test.tools.TestUtils.assertCursor(TestUtils.java:137)
2023-10-04T12:29:31.1426473Z 	at io.questdb.test.AbstractCairoTest.assertCursor(AbstractCairoTest.java:1524)
2023-10-04T12:29:31.1428003Z 	at io.questdb.test.AbstractCairoTest.assertCursorTwoPass(AbstractCairoTest.java:1528)
2023-10-04T12:29:31.1428469Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.assertTable(AbstractLineTcpReceiverTest.java:253)
2023-10-04T12:29:31.1428960Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.lambda$testRenameTable$26(LineTcpReceiverTest.java:727)
2023-10-04T12:29:31.1429410Z 	at io.questdb.test.tools.TestUtils.assertEventually(TestUtils.java:501)
2023-10-04T12:29:31.1429803Z 	at io.questdb.test.tools.TestUtils.assertEventually(TestUtils.java:491)
2023-10-04T12:29:31.1430224Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.lambda$testRenameTable$27(LineTcpReceiverTest.java:714)
2023-10-04T12:29:31.1430733Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.lambda$runInContext$2(AbstractLineTcpReceiverTest.java:299)
2023-10-04T12:29:31.1451793Z 	at io.questdb.test.AbstractCairoTest.lambda$assertMemoryLeak$7(AbstractCairoTest.java:923)
2023-10-04T12:29:31.1452271Z 	at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:568)
2023-10-04T12:29:31.1452690Z 	at io.questdb.test.AbstractCairoTest.assertMemoryLeak(AbstractCairoTest.java:920)
2023-10-04T12:29:31.1453302Z 	at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverTest.runInContext(AbstractLineTcpReceiverTest.java:291)
2023-10-04T12:29:31.1453800Z 	at io.questdb.test.cutlass.line.tcp.LineTcpReceiverTest.testRenameTable(LineTcpReceiverTest.java:700)
2023-10-04T12:29:31.1454196Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-10-04T12:29:31.1454596Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-10-04T12:29:31.1455248Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-10-04T12:29:31.1455654Z 	at java.lang.reflect.Method.invoke(Method.java:566)
2023-10-04T12:29:31.1456048Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-10-04T12:29:31.1456489Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-10-04T12:29:31.1456898Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-10-04T12:29:31.1457320Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-10-04T12:29:31.1457749Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-10-04T12:29:31.1458166Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-10-04T12:29:31.1458556Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2023-10-04T12:29:31.1458976Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
2023-10-04T12:29:31.1459435Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
2023-10-04T12:29:31.1459826Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-10-04T12:29:31.1460172Z 	at java.lang.Thread.run(Thread.java:829)
```

Full log:
[181.txt](https://github.com/questdb/questdb/files/12803526/181.txt)

### Expected Behavior

Test always passes

### Environment

```markdown
- **QuestDB version**:
- **OS**: Linux build
- **Browser**:
```

**Comment by puzpuzpuz** [comment] 2023-10-31 07:34
Seems to be a duplicate of #2990

**Closed by puzpuzpuz** 2023-10-31 07:34 UTC
