### ISSUE TITLE
UI JavaScript problem with Firefox

### ISSUE THREAD

**Issue by mrecht** [questdb/questdb#410] opened 2020-06-18 19:04 UTC
Using Firefox 77.0.1 on Windws 10 2004
64bit trying to resize the query panel does not work. It shows the error below in the debugger. Edge/Chromium works fine.
This is with 5.0.1-MASTER (commit 615f11abe18f417e75dd1c5d203b4b9f3f7059ab).

```
ReferenceError: TouchEvent is not defined qdb.js:88:3140
    A http://localhost:9000/qdb.js:88
    a http://localhost:9000/qdb.js:46
    f http://localhost:9000/qdb.js:46
    v http://localhost:9000/qdb.js:46
    v http://localhost:9000/qdb.js:46
    st http://localhost:9000/qdb.js:46
    rt http://localhost:9000/qdb.js:46
    at http://localhost:9000/qdb.js:46
    ft http://localhost:9000/qdb.js:46
    N http://localhost:9000/qdb.js:46
    z http://localhost:9000/qdb.js:46
    Jt http://localhost:9000/qdb.js:46
    Qt http://localhost:9000/qdb.js:46
    bind_applyFunctionN self-hosted:1042
    Qt self-hosted:1005
    unstable_runWithPriority http://localhost:9000/qdb.js:54
    Hr http://localhost:9000/qdb.js:46
    D http://localhost:9000/qdb.js:46
    Yt http://localhost:9000/qdb.js:46
    bind_applyFunctionN self-hosted:1042
    Yt self-hosted:1005
```

**Comment by mpsq** [comment] 2020-06-19 09:32
I can't reproduce this issue but I can see why this is happening. I will push a fix today, it will consist of defensive code and should hopefully be enough to prevent that from happening.

**Comment by mpsq** [comment] 2020-06-19 15:27
@mrecht this is now fixed on master, let me know if it works for you now :)

**Closed** 2020-06-19 15:44 UTC
Labels: UI, bug
