### ISSUE TITLE
Unique constraint for columns and upsert on conflict

### ISSUE THREAD

**Issue by DomnicAmalan** [questdb/questdb#1849] opened 2022-02-01 07:27 UTC
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

I would like to have a unique index constraint on columns

### Describe alternatives you've considered.

Timescale DB

**Comment by bsmth** [comment] 2022-02-01 09:07
Thanks for raising this. I'm going to close this one for now as it's a duplicate of https://github.com/questdb/questdb/issues/622

Thank you :)

**Closed by bsmth** 2022-02-01 09:07 UTC
Labels: New feature

**Comment by puzpuzpuz** [comment] 2022-02-01 09:16
My bad. I adviced @DomnicAmalan to open a feature request issue. Didn't consider that we might already have an issue for unique constraints.
