### ISSUE TITLE
SeqTxn is higher than WriterTxn all transactions are discarded

### ISSUE THREAD

**Issue by AbhinavChebrolu** [questdb/questdb#3372] opened 2023-05-20 07:58 UTC
### Describe the bug

After Windows ungracefully restarted after the automatic update _txn file started to have SeqTxn = 162965 and WriterTxn = 19349.

All transactions started to be silently ignored after this.

### Expected Behavior

Should not discard the transaction data but set table into suspended state instead.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

### Additional context

No response

**Comment by ideoma** [comment] 2023-05-22 09:14
This is by design.
Your best workaround is to convert table to non-WAL restart, convert to WAL restart.

https://questdb.io/docs/reference/sql/alter-table-set-type/

The underlying issues with ungrateful restarts are addressed https://github.com/questdb/questdb/pull/3304 and released in 7.1.2+

**Closed** 2023-05-22 09:14 UTC
