### ISSUE TITLE
CSV imports wrong timestamps

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#548] opened 2020-08-15 11:28 UTC
**Describe the bug**
Timestamps imported from CSV are wrong on every other row.

**To Reproduce**
1- try.questdb.io:9000
2- `SELECT pickup_datetime, passenger_count from trips limit 1000000;`
3- Download results as csv
4- Start QuestDB master locally
5- `CREATE TABLE test(pickup_datetime timestamp, passenger_count int)`
6- `COPY test from 'filename.csv'`

Note how each other timestamp is broken. However the file seems fine. It also seems to import more rows.

Original file
![Screenshot 2020-08-15 at 12 25 38](https://user-images.githubusercontent.com/52114895/90311419-9f0b6f00-def2-11ea-8653-155d2065faf1.png)

Import result
![Screenshot 2020-08-15 at 12 25 23](https://user-images.githubusercontent.com/52114895/90311420-a16dc900-def2-11ea-9ea4-d48c2d69bacf.png)

**Comment by bsmth** [comment] 2021-02-15 17:17
I cannot reproduce this, so it looks like it has been fixed in recent changes

**Closed by bsmth** 2021-02-15 17:17 UTC
Labels: bug
