### ISSUE TITLE
first() / last() implementation

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#363] opened 2020-06-04 16:25 UTC
**Is your feature request related to a problem? Please describe.**
the aggregation function `last()` only supports certain types (timestamp, long, int). However `last(symbol)` and `last(double)` for example are not supported.
`first()` is not implemented.

**Describe the solution you'd like**
Finish the implementation for `last` and implement `first`

**Comment by lbowman** [comment] 2020-07-02 12:59
I poked around with this today. `last(double)` is trivial, but `last(symbol)` and `last(str)` is going to have to go much deeper from what I see.

`GroupByFunction` passes `MapValue`(https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cairo/map/MapValue.java).

 - Not sure if we should be adding `putStr()` and `getStr()` to Record/MapValue interface and implementations. It looks like that needs to happen unless i'm implementing the wrong interface.

**Comment by bluestreak01** [comment] 2020-07-02 13:23
`last(symbol)` should be at the same complexity level as `last(double)`. Symbol values are stored as `int`. Its just a matter of remembering the last int value and then looking up symbol for that.

`last(string)` is more complicated -  yes, we can discuss that later

**Comment by lbowman** [comment] 2020-07-03 12:08
Fwiw I have a wip of this: https://github.com/lbowman/questdb/tree/feat.firstlast. I still need to understand the Symbol data type.

**Comment by TheTanc** [comment] 2020-07-05 20:10
Thanks Levi, if you need anything feel free to ask here or on Slack!

**Comment by lbowman** [comment] 2020-07-06 15:36
Added the basic First* group by functions.  I need to:

1. Add complete test coverage - (a) for where that is.
2. Cover more types short, symbol, maybe string.

(a) Currently when adding simple tests and running `mvn test` I get this:

```
Results :

Tests in error:
  LastDoubleGroupByFunctionFactoryTest>AbstractGriffinTest.assertMemoryLeak:488->AbstractGriffinTest.lambda$assertMemoryLeak$1:490 » Sql
  LastDoubleGroupByFunctionFactoryTest>AbstractGriffinTest.assertMemoryLeak:488->AbstractGriffinTest.lambda$assertMemoryLeak$1:490 » Sql
```

Test is simple: https://github.com/lbowman/questdb/blob/feat.firstlast/core/src/test/java/io/questdb/griffin/engine/functions/groupby/LastDoubleGroupByFunctionFactoryTest.java

**Comment by mpsq** [comment] 2020-07-15 11:58
I reviewed your code and I can't see anything wrong. @bluestreak01, can you have a look at it?
The diff is:
https://github.com/questdb/questdb/compare/master...lbowman:feat.firstlast

**Comment by bluestreak01** [comment] 2020-07-19 21:24
hey Levi, it looks like Maven Surefire plugin runs tests outside of Java module. These modules are never straightforward :(

To fix tests add your class to https://github.com/lbowman/questdb/blob/feat.firstlast/core/src/test/resources/META-INF/services/io.questdb.griffin.FunctionFactory

Last Symbol function would be very similar to Last Int as far as keeping track of value in map. To return `CharSequence` you function would subclass `SymbolFunction` and override this:

```java
public void init(SymbolTableSource symbolTableSource, SqlExecutionContext executionContext)
```

Here SymbolTableSource will help you to map int to CharSequence.

**Comment by lbowman** [comment] 2020-07-21 15:45
Thanks for the direction on tests and Symbol. I will complete tests and first/last Symbol and then we can discuss organization. It feels like many files/classes for not much functionality and maybe we should collapse some of this down.

**Comment by bluestreak01** [comment] 2020-07-23 12:59
You are right Levi, this is inspired by Java verbosity. We need to think of something indeed!

**Comment by lbowman** [comment] 2020-07-30 19:39
I have not had too much time to spend on this, but when I have tried to figure out first/lastSymbol I run into this: https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/cairo/sql/RecordCursor.java#L35
```
default SymbolTable getSymbolTable(int columnIndex) {
    throw new UnsupportedOperationException();
}
```

My class looks like:
`public class LastSymbolGroupByFunction extends SymbolFunction implements GroupByFunction, UnaryFunction {`

I'm happy to cleanup/commit what I have done or continue to pursue this.

**Comment by bluestreak01** [comment] 2020-07-30 22:49
This is an awesome spot Levi, thanks! You stumbled upon a bug.

This method was defaulted because there is a number of special case Cursors that do not have, or cannot have, symbol columns. Defaulting avoid duplication. But defaulting on the parent interface like that also hidden a bug:

RecordChain
FastMapCursor
CompactMapCursor

Must implement `getSymbolTable` but they don't. This is perhaps what you've stumbled upon executing a group-by SQL or a join

I am going to fix these issues and your functions should work as you'd expect.

**Comment by bluestreak01** [comment] 2020-07-31 01:34
i had a quick look and it seems that those cursors are always wrapped into another instance that does impl `getSymbolTable()`

it would be super helpful if you share full SQL that caused unsupported exception to be thrown or any other way to reproduce

**Comment by lbowman** [comment] 2020-07-31 15:26
I pushed my wip here: https://github.com/questdb/questdb/compare/master...lbowman:feat.firstlast

There is a test(not a complete test) which throws here: https://github.com/questdb/questdb/compare/master...lbowman:feat.firstlast#diff-9c49b7687efde88a8a8c0e9ee87cc920
```
create table tab as (select rnd_symbol(10, 4, 4, 0) sym from long_sequence(10))
select last(sym) from tab;
```

**Comment by bluestreak01** [comment] 2020-08-01 11:31
thanks Levi, this helps a lot. There seems to be a bug, where a bunch of group-by record cursor factories initialise their functions with own cursor rather than base cursor. This is something i can fix. Trouble is that to test the fix I would need to implement either first or last symbol. Looks like you have "last", so i will implement "first" :+1:

**Comment by lbowman** [comment] 2020-08-01 20:49
@bluestreak01 doesn't matter to me. In the current state I have all the Last* functions `extend First*` functions becuase what I have come across so far they are exactly the same outside of the `computeNext` method.  Won't hurt my feelings either way.

**Comment by bluestreak01** [comment] 2020-08-03 10:55
We just merged a bunch of fixes into master. There is example of FirstSymbol...:

https://github.com/questdb/questdb/blob/master/core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstSymbolGroupByFunction.java

Sorry I have mislead you to use SymbolTable. Symbol related calls should be delegated to the SymbolFunction arg. The latter has all the means to act like SymbolTable.

**Comment by bluestreak01** [comment] 2020-08-28 08:51
hey Levi, do you need a hand with getting this over the line?

**Comment by lbowman** [comment] 2020-08-31 18:17
I'll get back to this tomorrow.

**Comment by bluestreak01** [comment] 2020-09-04 14:35
hey Levi, thank you for your contribution! I implemented the missing bits, mainly tests on top of your commits:

https://github.com/questdb/questdb/pull/586

**Comment by bluestreak01** [comment] 2020-09-04 16:20
Levi, would you mind signing the CLA on #586 pls?

**Closed** 2020-09-06 19:16 UTC
Labels: New feature, SQL, good first issue
