### ISSUE TITLE
timestamp_sequence left join  result error

### ISSUE THREAD

**Issue by zhanghongbin** [questdb/questdb#2979] opened 2023-02-09 05:51 UTC
### Describe the bug

![1](https://user-images.githubusercontent.com/558610/217728796-2b9eb080-079b-4f24-bd1f-6090922029ea.png)

The timestamp_sequence and left join are used, and the result is wrong。

### To reproduce

1
```sql
create table  test_iot_data(
  value float,
  time timestamp
); 

2

insert into test_iot_data values(12,to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss'));
insert into test_iot_data values(13,dateadd('m', 18, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));
insert into test_iot_data values(14,dateadd('m', 78, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));
insert into test_iot_data values(15,dateadd('m', 189, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));

3

WITH grid AS (
   SELECT timestamp_sequence(to_timestamp('2023-02-09 00:00:00', 'yyyy-MM-dd HH:mm:ss'),100000L * 36000) AS t5 FROM long_sequence(24)
)
select grid.t5 as time,sum(value) as value  from grid left join  test_iot_data t on
t.time >= grid.t5 and
t.time < dateadd('m', 60, grid.t5)
order by time asc
```
### Expected Behavior

right result:
![2](https://user-images.githubusercontent.com/558610/217729015-81e0888c-7f98-4027-9884-74331109634d.png)
error result:
![1](https://user-images.githubusercontent.com/558610/217729035-328440b0-3638-48fd-bb1d-98ead83a9c4f.png)

### Environment

```markdown
- **QuestDB version:7**:
- **OS:windows**:
- **Browser:Firefox**:
```

**Comment by bziobrowski** [comment] 2023-02-09 08:08
Duplicate of #2555

**Comment by zhanghongbin** [comment] 2023-02-09 08:14
> Duplicate of #2555

hello,What should I do?

**Comment by bziobrowski** [comment] 2023-02-09 08:23
Results of random data generator functions are not stable between evaluations so they should only be used to insert data into tables.

Try : 

```sql
WITH grid AS (
   SELECT dateadd('h', (x-1)::int, '2023-02-09 00:00:00') AS t5 FROM long_sequence(24)
)
select grid.t5 as time,sum(value) as value  
from grid 
left join  test_iot_data t on t.time >= grid.t5 and t.time < dateadd('m', 60, grid.t5)
order by time asc
```

**Comment by bziobrowski** [comment] 2023-02-09 08:32
If you're dealing with lots of data, it'd be better to rewrite as : 

```sql
create table  test_iot_data(
  value float,
  time timestamp
) timestamp(time) partition by month;

insert into test_iot_data values(12,to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss'));
insert into test_iot_data values(13,dateadd('m', 18, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));
insert into test_iot_data values(14,dateadd('m', 78, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));
insert into test_iot_data values(15,dateadd('m', 189, to_timestamp('2023-02-09 00:30:00', 'yyyy-MM-dd HH:mm:ss')));

select timestamp_floor('h', t.time) as time, sum(value) as value  
from test_iot_data t
where t.time in '2023-02-09'
group by timestamp_floor('h', t.time)
order by 1 asc;
```

**Comment by zhanghongbin** [comment] 2023-02-09 08:41
This is not the result I want
![333](https://user-images.githubusercontent.com/558610/217760312-ce45af12-21d0-42e9-9b2b-239eb6097105.png)

The result I want is  **Keep the previous time interval**
![微信图片_20230209163700](https://user-images.githubusercontent.com/558610/217760382-d5e7b4a2-8b7a-4f86-918d-0331b1c4de2f.png)

**Comment by bziobrowski** [comment] 2023-02-09 08:48
Then left join with grid outside  group by query .

**Closed** 2023-04-17 14:23 UTC
