### ISSUE TITLE
Support for DEFAULT keyword in SQL

### ISSUE THREAD

**Issue by BTelghare07** [questdb/questdb#3199] opened 2023-04-16 12:22 UTC
### Describe the bug

CREATE TABLE "indicators" (
	"time" BIGINT NULL,
	"record_ts" TIMESTAMP DEFAULT '1969-12-31 23:59:59.999',
	"date" DATE DEFAULT '1969-12-31',
	"symbol" TEXT DEFAULT '',
	"event_type" TEXT DEFAULT '',
	"trade_price" DOUBLE PRECISION DEFAULT NaN,
	"trade_qty" DOUBLE PRECISION DEFAULT NaN,
	"trading_phase" TEXT DEFAULT '',
	"algo_state" TEXT DEFAULT '',
	"init_cl_ord_id" TEXT DEFAULT '',
	"volume" DOUBLE PRECISION DEFAULT NaN,
	"first_fill_time" TIMESTAMP NULL
)
create table does not recognise DEFAULT clause. We should implement it in two steps:

Support DEFAULT clause and ignore default values
Support actual default values in storage engine
Step 1 should be enough for most cases. Step 2 we should implement if there is enough demand.

### Environment

```markdown
- **QuestDB version**:
- **OS**:
- **Browser**:
```

**Comment by bziobrowski** [comment] 2023-04-17 07:16
Duplicate of #716

**Closed by bziobrowski** 2023-04-17 07:16 UTC
